/* =========================================================================
   NOVA QUIZ — extra content: True/False, Estimation, Top-Lists.
   TF:    { c, d, q, tf:true|false }
   EST:   { c, d, q, val:Number, unit:'' }
   LISTS: { c, d, topic, items:[accepted answers], n:targetCount, unit }
   ========================================================================= */
'use strict';

const TF = [
  { c:'allgemein', d:1, q:'Ein Dreieck hat drei Ecken.', tf:true },
  { c:'allgemein', d:1, q:'Die Sonne dreht sich um die Erde.', tf:false },
  { c:'allgemein', d:2, q:'Glas wird aus Sand hergestellt.', tf:true },
  { c:'allgemein', d:2, q:'Ein Kilometer hat 100 Meter.', tf:false },
  { c:'allgemein', d:1, q:'Wasser kocht bei 100 °C auf Meereshöhe.', tf:true },
  { c:'wissenschaft', d:2, q:'Schall breitet sich im Vakuum aus.', tf:false },
  { c:'wissenschaft', d:1, q:'Menschen haben fünf klassische Sinne.', tf:true },
  { c:'wissenschaft', d:3, q:'Diamant besteht aus reinem Kohlenstoff.', tf:true },
  { c:'wissenschaft', d:2, q:'Spinnen sind Insekten.', tf:false },
  { c:'wissenschaft', d:2, q:'Der Mensch nutzt nur 10 % seines Gehirns.', tf:false },
  { c:'wissenschaft', d:3, q:'Blut ist im Körper blau und wird rot an der Luft.', tf:false },
  { c:'natur', d:1, q:'Fische können ertrinken.', tf:false },
  { c:'natur', d:2, q:'Bananen wachsen an Bäumen.', tf:false },
  { c:'natur', d:2, q:'Ein Oktopus hat drei Herzen.', tf:true },
  { c:'natur', d:1, q:'Pinguine können fliegen.', tf:false },
  { c:'tiere', d:2, q:'Elefanten können nicht springen.', tf:true },
  { c:'tiere', d:2, q:'Eine Schnecke kann mehrere Jahre schlafen.', tf:true },
  { c:'tiere', d:1, q:'Kühe haben vier Mägen.', tf:true },
  { c:'tiere', d:3, q:'Haie sind Säugetiere.', tf:false },
  { c:'geografie', d:1, q:'Australien ist ein Land und ein Kontinent.', tf:true },
  { c:'geografie', d:2, q:'Der Nil fließt durch Ägypten.', tf:true },
  { c:'geografie', d:2, q:'Russland ist das größte Land der Erde.', tf:true },
  { c:'geografie', d:3, q:'Die Sahara ist die größte Wüste der Welt.', tf:false },
  { c:'geschichte', d:2, q:'Die Berliner Mauer fiel 1989.', tf:true },
  { c:'geschichte', d:2, q:'Die Pyramiden von Gizeh stehen in Mexiko.', tf:false },
  { c:'geschichte', d:3, q:'Der Zweite Weltkrieg endete 1945.', tf:true },
  { c:'weltraum', d:1, q:'Die Sonne ist ein Stern.', tf:true },
  { c:'weltraum', d:2, q:'Der Mars wird der "Rote Planet" genannt.', tf:true },
  { c:'weltraum', d:2, q:'Auf dem Mond gibt es Schwerkraft.', tf:true },
  { c:'weltraum', d:3, q:'Die Venus ist heißer als der Merkur.', tf:true },
  { c:'koerper', d:2, q:'Das Herz ist ein Muskel.', tf:true },
  { c:'koerper', d:2, q:'Erwachsene haben mehr Knochen als Babys.', tf:false },
  { c:'koerper', d:1, q:'Der Magen verdaut Nahrung.', tf:true },
  { c:'technik', d:1, q:'Eine SSD ist schneller als eine klassische Festplatte.', tf:true },
  { c:'technik', d:2, q:'WLAN überträgt Daten über Funk.', tf:true },
  { c:'technik', d:2, q:'HTML ist eine Programmiersprache zum Berechnen.', tf:false },
  { c:'sport', d:1, q:'Beim Tennis zählt man 15, 30, 40.', tf:true },
  { c:'sport', d:2, q:'Ein Fußballspiel dauert regulär 90 Minuten.', tf:true },
  { c:'sport', d:2, q:'Beim Basketball zählt ein Korb immer 3 Punkte.', tf:false },
  { c:'essen', d:1, q:'Honig wird von Bienen produziert.', tf:true },
  { c:'essen', d:2, q:'Tomaten sind botanisch gesehen Obst.', tf:true },
  { c:'essen', d:2, q:'Weiße Schokolade enthält Kakaobutter.', tf:true },
  { c:'musik', d:2, q:'Ein Klavier hat 88 Tasten.', tf:true },
  { c:'musik', d:2, q:'Eine Geige hat sechs Saiten.', tf:false },
  { c:'film', d:2, q:'Der Film "Titanic" wurde von James Cameron gedreht.', tf:true },
  { c:'gaming', d:2, q:'Mario ist eine Figur von Nintendo.', tf:true },
  { c:'gaming', d:2, q:'Minecraft wurde ursprünglich von Mojang entwickelt.', tf:true },
  { c:'mathe', d:1, q:'Eine gerade Zahl ist durch 2 teilbar.', tf:true },
  { c:'mathe', d:2, q:'Null ist eine Primzahl.', tf:false },
  { c:'mathe', d:2, q:'Ein Quadrat hat vier gleich lange Seiten.', tf:true },
  { c:'wirtschaft', d:2, q:'Der Euro ist die Währung mehrerer EU-Länder.', tf:true },
  { c:'wirtschaft', d:2, q:'Bitcoin ist eine physische Münze.', tf:false },
  { c:'aktuelles', d:2, q:'Die Olympischen Sommerspiele 2024 fanden in Paris statt.', tf:true },
  { c:'aktuelles', d:2, q:'Twitter wurde in "X" umbenannt.', tf:true },
  { c:'sprache', d:2, q:'"Lol" ist eine Abkürzung für lautes Lachen im Internet.', tf:true },
  { c:'mythologie', d:2, q:'Zeus ist der griechische Göttervater.', tf:true },
  { c:'mythologie', d:3, q:'Thor stammt aus der ägyptischen Mythologie.', tf:false },
  { c:'auto', d:2, q:'Tesla baut hauptsächlich Elektroautos.', tf:true },
  { c:'auto', d:2, q:'Ferrari ist eine deutsche Automarke.', tf:false },
  { c:'kunst', d:2, q:'Leonardo da Vinci malte die Mona Lisa.', tf:true },

  /* ===== EXPANSION: more True/False ===== */
  { c:'geografie', d:2, q:'Die Hauptstadt von Australien ist Sydney.', tf:false },
  { c:'geografie', d:1, q:'Afrika ist ein Kontinent.', tf:true },
  { c:'geografie', d:3, q:'Der Mount Everest ist der höchste Berg der Erde.', tf:true },
  { c:'geografie', d:2, q:'Es gibt mehr als 200 Länder auf der Welt.', tf:false },
  { c:'wissenschaft', d:2, q:'Gold ist ein chemisches Element.', tf:true },
  { c:'wissenschaft', d:3, q:'Ein Jahr auf der Venus ist kürzer als ein Tag dort.', tf:true },
  { c:'wissenschaft', d:1, q:'Eis ist gefrorenes Wasser.', tf:true },
  { c:'wissenschaft', d:2, q:'Der Mensch kann ohne Sauerstoff leben.', tf:false },
  { c:'tiere', d:2, q:'Ein Strauß ist der größte lebende Vogel.', tf:true },
  { c:'tiere', d:2, q:'Schmetterlinge schmecken mit den Füßen.', tf:true },
  { c:'tiere', d:3, q:'Ein Kolibri kann rückwärts fliegen.', tf:true },
  { c:'tiere', d:2, q:'Schildkröten haben Zähne.', tf:false },
  { c:'koerper', d:2, q:'Der Mensch hat zwei Nieren.', tf:true },
  { c:'koerper', d:3, q:'Niesen ist mit offenen Augen unmöglich.', tf:false },
  { c:'koerper', d:2, q:'Fingernägel wachsen schneller als Fußnägel.', tf:true },
  { c:'geschichte', d:2, q:'Die alten Ägypter bauten die Pyramiden.', tf:true },
  { c:'geschichte', d:3, q:'Albert Einstein erfand die Glühbirne.', tf:false },
  { c:'geschichte', d:2, q:'Die USA erklärten 1776 ihre Unabhängigkeit.', tf:true },
  { c:'sport', d:2, q:'Beim Boxen gibt es Runden.', tf:true },
  { c:'sport', d:3, q:'Ein Tennismatch kann unentschieden enden.', tf:false },
  { c:'sport', d:2, q:'Die Tour de France ist ein Radrennen.', tf:true },
  { c:'technik', d:2, q:'Ein QR-Code kann Informationen speichern.', tf:true },
  { c:'technik', d:2, q:'USB steht für "Universal Serial Bus".', tf:true },
  { c:'technik', d:3, q:'Die erste E-Mail wurde in den 1970ern verschickt.', tf:true },
  { c:'weltraum', d:2, q:'Die Erde ist der dritte Planet von der Sonne.', tf:true },
  { c:'weltraum', d:3, q:'Auf dem Mars gibt es flüssiges Wasser an der Oberfläche.', tf:false },
  { c:'weltraum', d:2, q:'Der Mond leuchtet aus eigener Kraft.', tf:false },
  { c:'essen', d:2, q:'Karotten sind gut für die Augen.', tf:true },
  { c:'essen', d:3, q:'Honig kann nicht verderben.', tf:true },
  { c:'essen', d:2, q:'Erdnüsse sind Nüsse.', tf:false },
  { c:'film', d:2, q:'Yoda kommt in Star Wars vor.', tf:true },
  { c:'gaming', d:2, q:'Tetris stammt ursprünglich aus Russland.', tf:true },
  { c:'gaming', d:2, q:'Pac-Man ist ein Rennspiel.', tf:false },
  { c:'mathe', d:2, q:'Die Summe der Innenwinkel eines Dreiecks ist 180°.', tf:true },
  { c:'mathe', d:2, q:'Jede Primzahl ist ungerade.', tf:false },
  { c:'mathe', d:3, q:'Pi ist eine irrationale Zahl.', tf:true },
  { c:'wirtschaft', d:2, q:'Amazon begann als Online-Buchhandlung.', tf:true },
  { c:'wirtschaft', d:3, q:'Der NASDAQ ist eine Börse.', tf:true },
  { c:'sprache', d:2, q:'Englisch ist die meistgesprochene Muttersprache der Welt.', tf:false },
  { c:'mythologie', d:2, q:'Herkules ist für seine Stärke bekannt.', tf:true },
];

const EST = [
  { c:'geografie', d:2, q:'Wie hoch ist der Mount Everest (in Metern)?', val:8849, unit:'m' },
  { c:'geografie', d:2, q:'Wie viele Länder hat Afrika (ca.)?', val:54, unit:'' },
  { c:'geografie', d:3, q:'Wie lang ist der Nil (in km, ca.)?', val:6650, unit:'km' },
  { c:'geografie', d:2, q:'Wie viele Einwohner hat Deutschland (in Millionen, ca.)?', val:84, unit:'Mio.' },
  { c:'geografie', d:3, q:'Wie tief ist der Marianengraben (in Metern, ca.)?', val:11000, unit:'m' },
  { c:'weltraum', d:2, q:'Wie viele Monde hat der Mars?', val:2, unit:'' },
  { c:'weltraum', d:3, q:'Wie weit ist die Sonne von der Erde entfernt (in Mio. km, ca.)?', val:150, unit:'Mio. km' },
  { c:'weltraum', d:3, q:'Wie viele Erden würden ungefähr in die Sonne passen?', val:1300000, unit:'' },
  { c:'koerper', d:2, q:'Wie viele Knochen hat ein erwachsener Mensch?', val:206, unit:'' },
  { c:'koerper', d:3, q:'Wie oft schlägt ein menschliches Herz pro Tag (ca.)?', val:100000, unit:'' },
  { c:'koerper', d:2, q:'Wie viel Prozent des menschlichen Körpers besteht aus Wasser (ca.)?', val:60, unit:'%' },
  { c:'wissenschaft', d:2, q:'Bei wie viel °C gefriert Wasser?', val:0, unit:'°C' },
  { c:'wissenschaft', d:3, q:'Wie schnell ist Licht (in km/s, ca.)?', val:300000, unit:'km/s' },
  { c:'wissenschaft', d:2, q:'Wie viele Elemente hat das Periodensystem (ca.)?', val:118, unit:'' },
  { c:'geschichte', d:2, q:'In welchem Jahr fiel die Berliner Mauer?', val:1989, unit:'' },
  { c:'geschichte', d:2, q:'In welchem Jahr endete der Zweite Weltkrieg?', val:1945, unit:'' },
  { c:'geschichte', d:3, q:'In welchem Jahr sank die Titanic?', val:1912, unit:'' },
  { c:'sport', d:2, q:'Wie lang ist ein Marathon (in km, eine Nachkommastelle ok)?', val:42, unit:'km' },
  { c:'sport', d:2, q:'Wie viele Spieler hat eine Fußballmannschaft auf dem Feld?', val:11, unit:'' },
  { c:'sport', d:3, q:'Wie viele Teilnehmerländer hatte die Fußball-WM 2022?', val:32, unit:'' },
  { c:'natur', d:2, q:'Wie alt kann ein Mammutbaum werden (in Jahren, ca.)?', val:3000, unit:'Jahre' },
  { c:'tiere', d:2, q:'Wie schnell rennt ein Gepard (in km/h, ca.)?', val:110, unit:'km/h' },
  { c:'tiere', d:3, q:'Wie viele Herzen hat ein Regenwurm (ca.)?', val:5, unit:'' },
  { c:'tiere', d:2, q:'Wie lange ist ein Blauwal (in Metern, ca.)?', val:30, unit:'m' },
  { c:'technik', d:2, q:'Wie viele Bit hat ein Byte?', val:8, unit:'' },
  { c:'technik', d:3, q:'In welchem Jahr wurde das erste iPhone vorgestellt?', val:2007, unit:'' },
  { c:'essen', d:2, q:'Wie viele Kalorien hat ein Apfel (mittelgroß, ca.)?', val:95, unit:'kcal' },
  { c:'wirtschaft', d:3, q:'Wie viele Nullen hat eine Milliarde?', val:9, unit:'' },
  { c:'allgemein', d:1, q:'Wie viele Sekunden hat eine Minute?', val:60, unit:'' },
  { c:'allgemein', d:2, q:'Wie viele Knochen... äh, wie viele Tage hat ein Schaltjahr?', val:366, unit:'' },
  { c:'allgemein', d:2, q:'Wie viele Buchstaben hat das deutsche Alphabet (ohne Umlaute/ß)?', val:26, unit:'' },
  { c:'musik', d:2, q:'Wie viele Tasten hat ein Standard-Klavier?', val:88, unit:'' },
  { c:'film', d:3, q:'Wie viele "Star Wars"-Hauptfilme (Skywalker-Saga) gibt es?', val:9, unit:'' },
  { c:'weltraum', d:2, q:'Wie viele Planeten hat das Sonnensystem?', val:8, unit:'' },
  { c:'mathe', d:2, q:'Was ist 12 × 12?', val:144, unit:'' },
  { c:'mathe', d:3, q:'Was ergibt 2 hoch 10?', val:1024, unit:'' },
  { c:'geografie', d:3, q:'Wie viele Zeitzonen gibt es weltweit (ca.)?', val:24, unit:'' },
  { c:'koerper', d:3, q:'Wie viele Muskeln hat der menschliche Körper (ca.)?', val:640, unit:'' },
  { c:'geografie', d:2, q:'Wie viele Bundesländer hat Deutschland?', val:16, unit:'' },
  { c:'geografie', d:3, q:'Wie viele Mitgliedsstaaten hat die EU (Stand 2024)?', val:27, unit:'' },

  /* ===== EXPANSION: more Estimation ===== */
  { c:'geografie', d:2, q:'Wie viele Kontinente gibt es?', val:7, unit:'' },
  { c:'geografie', d:3, q:'Wie viele Länder gibt es ungefähr auf der Welt?', val:195, unit:'' },
  { c:'geografie', d:3, q:'Wie groß ist die Erde am Äquator im Umfang (in km, ca.)?', val:40075, unit:'km' },
  { c:'geografie', d:2, q:'Wie viele Einwohner hat die Erde (in Milliarden, ca.)?', val:8, unit:'Mrd.' },
  { c:'koerper', d:2, q:'Wie viele Zähne hat ein Erwachsener?', val:32, unit:'' },
  { c:'koerper', d:3, q:'Wie viele Liter Blut hat ein Erwachsener ungefähr?', val:5, unit:'l' },
  { c:'koerper', d:3, q:'Wie viele Chromosomenpaare hat der Mensch?', val:23, unit:'' },
  { c:'wissenschaft', d:2, q:'Bei wie viel °C kocht Wasser auf Meereshöhe?', val:100, unit:'°C' },
  { c:'wissenschaft', d:3, q:'Wie viele Beine hat eine Spinne?', val:8, unit:'' },
  { c:'tiere', d:2, q:'Wie viele Zähne hat ein erwachsener Hund ungefähr?', val:42, unit:'' },
  { c:'tiere', d:3, q:'Wie lange ist die Tragezeit eines Elefanten (in Monaten, ca.)?', val:22, unit:'Monate' },
  { c:'tiere', d:2, q:'Wie viele Eier legt ein Huhn etwa pro Jahr?', val:300, unit:'' },
  { c:'sport', d:2, q:'Wie viele Minuten dauert eine Halbzeit beim Fußball?', val:45, unit:'min' },
  { c:'sport', d:2, q:'Wie viele Spieler stehen beim Basketball pro Team auf dem Feld?', val:5, unit:'' },
  { c:'sport', d:3, q:'Wie viele olympische Goldmedaillen gewann Michael Phelps insgesamt?', val:23, unit:'' },
  { c:'geschichte', d:2, q:'In welchem Jahr begann der Erste Weltkrieg?', val:1914, unit:'' },
  { c:'geschichte', d:3, q:'In welchem Jahr landete der erste Mensch auf dem Mond?', val:1969, unit:'' },
  { c:'geschichte', d:2, q:'In welchem Jahr wurde Amerika von Kolumbus "entdeckt"?', val:1492, unit:'' },
  { c:'weltraum', d:2, q:'Wie viele Minuten braucht das Sonnenlicht bis zur Erde (ca.)?', val:8, unit:'min' },
  { c:'weltraum', d:3, q:'Wie viele bekannte Monde hat der Jupiter (ca.)?', val:95, unit:'' },
  { c:'technik', d:2, q:'Wie viele Megabyte hat ein Gigabyte?', val:1024, unit:'MB' },
  { c:'technik', d:3, q:'In welchem Jahr wurde Google gegründet?', val:1998, unit:'' },
  { c:'allgemein', d:1, q:'Wie viele Stunden hat ein Tag?', val:24, unit:'' },
  { c:'allgemein', d:1, q:'Wie viele Monate hat ein Jahr?', val:12, unit:'' },
  { c:'allgemein', d:2, q:'Wie viele Tasten hat eine Standard-PC-Tastatur (ca.)?', val:105, unit:'' },
  { c:'mathe', d:2, q:'Was ist 25 × 4?', val:100, unit:'' },
  { c:'mathe', d:3, q:'Wie viele Sekunden hat eine Stunde?', val:3600, unit:'' },
  { c:'essen', d:2, q:'Wie viele Gramm hat ein Kilogramm?', val:1000, unit:'g' },
  { c:'wirtschaft', d:3, q:'Wie viele Nullen hat eine Million?', val:6, unit:'' },
  { c:'kunst', d:3, q:'In welchem Jahrhundert lebte William Shakespeare (16.–17.)?', val:16, unit:'.Jh.' },
];

const LISTS = [
  { c:'weltraum', d:1, topic:'Nenne Planeten unseres Sonnensystems', items:['merkur','venus','erde','mars','jupiter','saturn','uranus','neptun'], n:8 },
  { c:'allgemein', d:1, topic:'Nenne die Farben des Regenbogens', items:['rot','orange','gelb','grün','blau','indigo','violett'], n:7 },
  { c:'geografie', d:1, topic:'Nenne die Kontinente', items:['europa','asien','afrika','nordamerika','südamerika','australien','ozeanien','antarktis','antarktika'], n:7 },
  { c:'allgemein', d:1, topic:'Nenne die Wochentage', items:['montag','dienstag','mittwoch','donnerstag','freitag','samstag','sonntag'], n:7 },
  { c:'allgemein', d:2, topic:'Nenne Monate des Jahres', items:['januar','februar','märz','april','mai','juni','juli','august','september','oktober','november','dezember'], n:8 },
  { c:'geografie', d:2, topic:'Nenne Nachbarländer Deutschlands', items:['frankreich','österreich','schweiz','polen','tschechien','dänemark','niederlande','belgien','luxemburg'], n:7 },
  { c:'geografie', d:3, topic:'Nenne deutsche Bundesländer', items:['bayern','baden-württemberg','hessen','niedersachsen','nordrhein-westfalen','nrw','rheinland-pfalz','saarland','sachsen','sachsen-anhalt','thüringen','brandenburg','mecklenburg-vorpommern','schleswig-holstein','berlin','hamburg','bremen'], n:8 },
  { c:'film', d:1, topic:'Nenne die Häuser in Harry Potter', items:['gryffindor','slytherin','hufflepuff','ravenclaw'], n:4 },
  { c:'musik', d:2, topic:'Nenne Mitglieder der Beatles', items:['john lennon','paul mccartney','george harrison','ringo starr','lennon','mccartney','harrison','starr'], n:4 },
  { c:'sport', d:1, topic:'Nenne die Farben der olympischen Ringe', items:['blau','gelb','schwarz','grün','rot'], n:5 },
  { c:'essen', d:1, topic:'Nenne beliebte Pizzabeläge', items:['käse','salami','schinken','pilze','champignons','peperoni','zwiebeln','paprika','ananas','tomaten','oliven','thunfisch','sardellen','rucola','spinat','hähnchen'], n:8 },
  { c:'essen', d:1, topic:'Nenne beliebte Obstsorten', items:['apfel','banane','orange','erdbeere','traube','weintraube','birne','kirsche','pfirsich','melone','ananas','mango','kiwi','zitrone','himbeere','blaubeere','pflaume'], n:8 },
  { c:'essen', d:1, topic:'Nenne beliebte Gemüsesorten', items:['karotte','möhre','tomate','gurke','kartoffel','zwiebel','paprika','brokkoli','salat','spinat','zucchini','aubergine','kohl','blumenkohl','erbse','bohne','mais'], n:8 },
  { c:'essen', d:2, topic:'Nenne beliebte Lebensmittel im Supermarkt', items:['milch','brot','eier','butter','käse','wurst','obst','gemüse','nudeln','reis','mehl','zucker','kaffee','tee','wasser','saft','joghurt','fleisch','fisch','schokolade','chips'], n:10 },
  { c:'essen', d:2, topic:'Nenne beliebte Eissorten', items:['vanille','schokolade','erdbeere','stracciatella','zitrone','haselnuss','pistazie','mango','cookie','karamell','joghurt','banane','kirsche'], n:8 },
  { c:'essen', d:2, topic:'Nenne beliebte Heißgetränke', items:['kaffee','tee','kakao','espresso','cappuccino','latte','glühwein','milchkaffee','grüner tee'], n:6 },
  { c:'natur', d:2, topic:'Nenne Planeten mit Ringen', items:['saturn','jupiter','uranus','neptun'], n:4 },
  { c:'sport', d:2, topic:'Nenne beliebte Ballsportarten', items:['fußball','basketball','handball','volleyball','tennis','tischtennis','golf','baseball','rugby','football','wasserball'], n:8 },
  { c:'sport', d:3, topic:'Nenne Länder, die Fußball-Weltmeister wurden', items:['brasilien','deutschland','italien','argentinien','frankreich','uruguay','england','spanien'], n:8 },
  { c:'film', d:2, topic:'Nenne Avengers (Marvel)', items:['iron man','captain america','thor','hulk','black widow','hawkeye','spider-man','black panther','doctor strange','ant-man','scarlet witch','vision','captain marvel','war machine','falcon'], n:8 },
  { c:'film', d:3, topic:'Nenne Star-Wars-Figuren', items:['luke skywalker','darth vader','yoda','han solo','leia','chewbacca','obi-wan','r2-d2','c-3po','kylo ren','rey','finn','palpatine','boba fett','anakin'], n:8 },
  { c:'wirtschaft', d:2, topic:'Nenne bekannte Tech-Unternehmen', items:['apple','google','microsoft','amazon','meta','facebook','samsung','tesla','nvidia','intel','ibm','sony','netflix','oracle'], n:8 },
  { c:'wirtschaft', d:2, topic:'Nenne bekannte Automarken', items:['mercedes','bmw','audi','volkswagen','vw','toyota','ford','ferrari','porsche','tesla','opel','honda','nissan','hyundai','renault','fiat','mazda','kia','volvo'], n:10 },
  { c:'wirtschaft', d:2, topic:'Nenne beliebte Social-Media-Apps', items:['instagram','tiktok','facebook','youtube','snapchat','x','twitter','whatsapp','telegram','reddit','pinterest','linkedin','discord','threads'], n:8 },
  { c:'wirtschaft', d:2, topic:'Nenne beliebte Streaming-Dienste', items:['netflix','disney+','disney plus','amazon prime','prime video','youtube','spotify','apple tv','hbo','max','paramount','dazn','sky','wow'], n:7 },
  { c:'wirtschaft', d:3, topic:'Nenne bekannte Fast-Food-Ketten', items:['mcdonalds','mcdonald’s','burger king','kfc','subway','dominos','pizza hut','starbucks','five guys','wendys','taco bell'], n:7 },
  { c:'gaming', d:2, topic:'Nenne beliebte Videospiele', items:['minecraft','fortnite','gta','call of duty','fifa','roblox','league of legends','valorant','the witcher','zelda','mario','pokemon','counter-strike','overwatch','among us','tetris'], n:8 },
  { c:'gaming', d:2, topic:'Nenne Spielkonsolen-Hersteller', items:['sony','microsoft','nintendo','sega','atari'], n:4 },
  { c:'gaming', d:3, topic:'Nenne Nintendo-Konsolen', items:['switch','wii','wii u','gamecube','n64','nintendo 64','snes','nes','gameboy','game boy','ds','3ds'], n:7 },
  { c:'geografie', d:2, topic:'Nenne die größten Länder der Welt (Fläche)', items:['russland','kanada','usa','china','brasilien','australien','indien','argentinien','kasachstan','algerien'], n:7 },
  { c:'geografie', d:3, topic:'Nenne die bevölkerungsreichsten Länder', items:['indien','china','usa','indonesien','pakistan','nigeria','brasilien','bangladesch','russland','mexiko'], n:7 },
  { c:'geografie', d:2, topic:'Nenne Ozeane der Erde', items:['pazifik','atlantik','indischer ozean','arktischer ozean','südlicher ozean','antarktischer ozean'], n:5 },
  { c:'geografie', d:3, topic:'Nenne europäische Hauptstädte', items:['berlin','paris','madrid','rom','london','wien','amsterdam','brüssel','lissabon','warschau','prag','budapest','athen','dublin','stockholm','oslo','kopenhagen','helsinki','bern'], n:10 },
  { c:'natur', d:2, topic:'Nenne Raubkatzen', items:['löwe','tiger','leopard','gepard','jaguar','puma','luchs','panther','schneeleopard'], n:6 },
  { c:'tiere', d:2, topic:'Nenne Haustiere', items:['hund','katze','hamster','kaninchen','hase','meerschweinchen','vogel','wellensittich','fisch','goldfisch','schildkröte','maus','ratte','pferd'], n:7 },
  { c:'tiere', d:2, topic:'Nenne Meerestiere', items:['hai','wal','delfin','delphin','oktopus','krake','qualle','seestern','krabbe','hummer','tintenfisch','seepferdchen','rochen','thunfisch','robbe'], n:8 },
  { c:'tiere', d:2, topic:'Nenne Vogelarten', items:['adler','spatz','taube','amsel','meise','specht','eule','falke','pinguin','flamingo','papagei','schwan','ente','gans','rabe','krähe','storch'], n:8 },
  { c:'koerper', d:2, topic:'Nenne die fünf menschlichen Sinne', items:['sehen','hören','riechen','schmecken','tasten','fühlen','gehör','geruch','geschmack','sicht'], n:5 },
  { c:'koerper', d:2, topic:'Nenne Organe des Menschen', items:['herz','lunge','leber','niere','magen','gehirn','haut','darm','milz','bauchspeicheldrüse','blase'], n:8 },
  { c:'mythologie', d:3, topic:'Nenne griechische Götter', items:['zeus','poseidon','hades','athene','apollon','ares','hermes','aphrodite','artemis','hera','demeter','dionysos','hephaistos'], n:8 },
  { c:'musik', d:2, topic:'Nenne Musikinstrumente', items:['gitarre','klavier','geige','schlagzeug','flöte','trompete','bass','saxophon','cello','harfe','klarinette','posaune','keyboard','akkordeon'], n:8 },
  { c:'musik', d:3, topic:'Nenne Musikgenres', items:['pop','rock','rap','hip hop','jazz','klassik','techno','house','metal','reggae','blues','country','schlager','electro','punk','soul'], n:8 },
  { c:'film', d:2, topic:'Nenne Disney-Filme', items:['der könig der löwen','aladdin','frozen','die eiskönigin','findet nemo','toy story','cinderella','arielle','dumbo','bambi','tarzan','mulan','vaiana','encanto','zoomania'], n:8 },
  { c:'film', d:3, topic:'Nenne Filmgenres', items:['action','komödie','horror','drama','science fiction','sci-fi','thriller','western','fantasy','romanze','animation','musical','krimi','abenteuer','dokumentation'], n:8 },
  { c:'sprache', d:2, topic:'Nenne Weltsprachen (meistgesprochen)', items:['englisch','chinesisch','mandarin','spanisch','hindi','arabisch','französisch','russisch','portugiesisch','bengalisch','deutsch','japanisch'], n:7 },
  { c:'kunst', d:3, topic:'Nenne berühmte Maler', items:['van gogh','picasso','da vinci','leonardo da vinci','monet','rembrandt','michelangelo','dalí','dali','warhol','klimt','vermeer','frida kahlo','munch'], n:7 },
  { c:'geschichte', d:3, topic:'Nenne antike Weltwunder', items:['pyramiden','hängende gärten','zeusstatue','artemistempel','mausoleum','koloss von rhodos','koloss','leuchtturm von alexandria','leuchtturm'], n:6 },
  { c:'allgemein', d:2, topic:'Nenne Schachfiguren', items:['könig','dame','turm','läufer','springer','bauer','pferd'], n:6 },
  { c:'allgemein', d:2, topic:'Nenne die Grundfarben (subtraktiv/Malen)', items:['rot','gelb','blau'], n:3 },
  { c:'natur', d:2, topic:'Nenne Wetterphänomene', items:['regen','schnee','hagel','sturm','gewitter','nebel','sonne','wind','blitz','donner','tornado','regenbogen','frost','tau'], n:8 },
  { c:'natur', d:2, topic:'Nenne Edelmetalle/Edelsteine', items:['gold','silber','platin','diamant','rubin','saphir','smaragd','bernstein','perle','topas','amethyst'], n:6 },
  { c:'sport', d:2, topic:'Nenne olympische Sportarten', items:['schwimmen','leichtathletik','turnen','fechten','rudern','radfahren','boxen','judo','tennis','basketball','volleyball','handball','reiten','segeln','gewichtheben'], n:8 },
  { c:'wirtschaft', d:3, topic:'Nenne Kryptowährungen', items:['bitcoin','ethereum','dogecoin','litecoin','ripple','cardano','solana','tether','bnb','shiba'], n:6 },
  { c:'aktuelles', d:2, topic:'Nenne KI-Chatbots / KI-Tools', items:['chatgpt','gemini','claude','copilot','grok','llama','midjourney','dall-e','bard'], n:6 },
  { c:'essen', d:2, topic:'Nenne Käsesorten', items:['gouda','edamer','emmentaler','mozzarella','parmesan','feta','camembert','brie','cheddar','gorgonzola','ricotta','frischkäse'], n:8 },
  { c:'essen', d:2, topic:'Nenne Nudelsorten', items:['spaghetti','penne','fusilli','farfalle','tagliatelle','lasagne','makkaroni','ravioli','tortellini','rigatoni','gnocchi'], n:7 },
  { c:'geografie', d:3, topic:'Nenne die größten Städte der Welt', items:['tokio','delhi','shanghai','são paulo','mexiko-stadt','kairo','mumbai','peking','new york','istanbul'], n:7 },
  { c:'welt', d:3, topic:'Nenne Inselstaaten', items:['japan','island','irland','kuba','madagaskar','sri lanka','neuseeland','philippinen','indonesien','malta','zypern','jamaika','fidschi'], n:7 },

  /* ===== EXPANSION: more Top-Lists ===== */
  { c:'essen', d:2, topic:'Nenne beliebte Fastfood-Gerichte', items:['burger','pommes','pizza','hotdog','döner','nuggets','wrap','sandwich','taco','currywurst','chicken'], n:7 },
  { c:'essen', d:2, topic:'Nenne Frühstücksklassiker', items:['brötchen','müsli','ei','rührei','spiegelei','marmelade','croissant','pancakes','toast','haferflocken','speck','joghurt','obst'], n:8 },
  { c:'essen', d:2, topic:'Nenne Getränke ohne Alkohol', items:['wasser','cola','limonade','saft','tee','kaffee','kakao','eistee','sprudel','smoothie','milch','fanta','sprite'], n:8 },
  { c:'essen', d:3, topic:'Nenne Gewürze', items:['salz','pfeffer','paprika','curry','zimt','kümmel','muskat','oregano','basilikum','thymian','chili','ingwer','knoblauch','vanille','safran'], n:8 },
  { c:'natur', d:2, topic:'Nenne Bäume', items:['eiche','buche','birke','tanne','fichte','kiefer','ahorn','linde','kastanie','weide','pappel','ulme','esche','platane'], n:8 },
  { c:'natur', d:2, topic:'Nenne Blumen', items:['rose','tulpe','sonnenblume','gänseblümchen','nelke','lilie','orchidee','veilchen','narzisse','margerite','flieder','mohn'], n:8 },
  { c:'tiere', d:2, topic:'Nenne Insekten', items:['biene','wespe','ameise','käfer','fliege','mücke','schmetterling','libelle','grille','heuschrecke','marienkäfer','hummel'], n:8 },
  { c:'tiere', d:2, topic:'Nenne Reptilien', items:['schlange','krokodil','eidechse','schildkröte','gecko','leguan','chamäleon','alligator','waran'], n:6 },
  { c:'tiere', d:3, topic:'Nenne Dinosaurier', items:['tyrannosaurus','t-rex','triceratops','velociraptor','brachiosaurus','stegosaurus','diplodocus','spinosaurus','pteranodon','ankylosaurus'], n:6 },
  { c:'sport', d:2, topic:'Nenne Wintersportarten', items:['ski','skifahren','snowboard','eishockey','eiskunstlauf','rodeln','bob','biathlon','langlauf','curling','skispringen','eisschnelllauf'], n:7 },
  { c:'sport', d:3, topic:'Nenne berühmte Fußballer', items:['messi','ronaldo','neymar','mbappé','müller','maradona','pelé','beckham','zidane','ronaldinho','lewandowski','kroos','haaland'], n:7 },
  { c:'sport', d:3, topic:'Nenne Formel-1-Weltmeister', items:['hamilton','schumacher','vettel','verstappen','alonso','senna','prost','rosberg','räikkönen','häkkinen','lauda'], n:6 },
  { c:'geografie', d:2, topic:'Nenne afrikanische Länder', items:['ägypten','nigeria','südafrika','kenia','marokko','algerien','ghana','äthiopien','tansania','tunesien','angola','kongo','senegal'], n:7 },
  { c:'geografie', d:2, topic:'Nenne asiatische Länder', items:['china','japan','indien','thailand','vietnam','südkorea','indonesien','philippinen','pakistan','türkei','iran','saudi-arabien','malaysia'], n:8 },
  { c:'geografie', d:2, topic:'Nenne europäische Länder', items:['deutschland','frankreich','italien','spanien','polen','niederlande','belgien','schweden','norwegen','griechenland','portugal','österreich','schweiz','irland','dänemark','finnland'], n:10 },
  { c:'geografie', d:3, topic:'Nenne Flüsse in Europa', items:['rhein','donau','elbe','seine','themse','wolga','po','rhone','loire','oder','main','mosel','tiber'], n:7 },
  { c:'geografie', d:3, topic:'Nenne Gebirge der Welt', items:['alpen','himalaya','anden','rocky mountains','pyrenäen','karpaten','ural','kaukasus','atlas','appalachen'], n:6 },
  { c:'film', d:2, topic:'Nenne Pixar-Filme', items:['toy story','findet nemo','cars','oben','wall-e','ratatouille','die unglaublichen','coco','soul','alles steht kopf','monster ag','findet dorie'], n:7 },
  { c:'film', d:3, topic:'Nenne Superhelden', items:['superman','batman','spider-man','iron man','hulk','thor','wonder woman','flash','captain america','aquaman','black panther','wolverine','deadpool'], n:8 },
  { c:'musik', d:3, topic:'Nenne berühmte Bands', items:['beatles','queen','rolling stones','abba','u2','coldplay','metallica','nirvana','ac/dc','led zeppelin','pink floyd','linkin park','imagine dragons'], n:7 },
  { c:'musik', d:3, topic:'Nenne berühmte Sänger/innen', items:['michael jackson','madonna','beyoncé','taylor swift','elvis','ed sheeran','rihanna','adele','bruno mars','justin bieber','lady gaga','drake','eminem'], n:8 },
  { c:'gaming', d:2, topic:'Nenne Pokémon', items:['pikachu','glumanda','schiggy','bisasam','evoli','enton','relaxo','mewtu','mew','rattfratz','taubsi','karpador','garados'], n:7 },
  { c:'gaming', d:3, topic:'Nenne Spielentwickler/Studios', items:['nintendo','rockstar','ubisoft','ea','electronic arts','activision','valve','mojang','cd projekt','epic games','blizzard','bethesda','sega','capcom'], n:7 },
  { c:'mythologie', d:3, topic:'Nenne nordische Götter', items:['odin','thor','loki','freya','baldur','heimdall','tyr','frigg','njörd','hel'], n:6 },
  { c:'mythologie', d:3, topic:'Nenne Fabelwesen', items:['drache','einhorn','phönix','zentaur','minotaurus','greif','meerjungfrau','elf','zwerg','troll','werwolf','vampir','kobold','sphinx'], n:8 },
  { c:'wirtschaft', d:2, topic:'Nenne Sportmarken', items:['nike','adidas','puma','under armour','reebok','new balance','asics','fila','jordan'], n:6 },
  { c:'wirtschaft', d:3, topic:'Nenne Modemarken/Luxus', items:['gucci','prada','chanel','louis vuitton','dior','versace','armani','hermès','rolex','burberry'], n:6 },
  { c:'koerper', d:2, topic:'Nenne Körperteile', items:['kopf','arm','bein','hand','fuß','finger','nase','ohr','auge','mund','knie','schulter','ellbogen','bauch','rücken'], n:8 },
  { c:'koerper', d:3, topic:'Nenne Knochen im Körper', items:['schädel','wirbelsäule','rippen','becken','oberschenkel','schienbein','wadenbein','oberarm','elle','speiche','schlüsselbein','kniescheibe'], n:6 },
  { c:'weltraum', d:2, topic:'Nenne Dinge im Weltall', items:['stern','planet','mond','komet','asteroid','galaxie','schwarzes loch','nebel','sonne','meteorit','satellit','rakete'], n:7 },
  { c:'sprache', d:2, topic:'Nenne Begrüßungen in anderen Sprachen', items:['hello','hola','bonjour','ciao','hallo','hi','salut','konnichiwa','namaste','aloha','privet','hej'], n:7 },
  { c:'allgemein', d:2, topic:'Nenne Planeten und Zwergplaneten', items:['merkur','venus','erde','mars','jupiter','saturn','uranus','neptun','pluto','ceres','eris'], n:8 },
  { c:'allgemein', d:2, topic:'Nenne Jahreszeiten', items:['frühling','sommer','herbst','winter'], n:4 },
  { c:'allgemein', d:2, topic:'Nenne Himmelsrichtungen', items:['norden','osten','süden','westen','nordosten','südosten','südwesten','nordwesten'], n:4 },
  { c:'kunst', d:3, topic:'Nenne berühmte Schriftsteller', items:['goethe','schiller','shakespeare','kafka','hemingway','tolkien','rowling','king','dostojewski','hesse','brecht','mann','grass'], n:7 },
  { c:'geschichte', d:3, topic:'Nenne historische Persönlichkeiten', items:['napoleon','cäsar','kleopatra','einstein','newton','gandhi','luther','columbus','alexander der große','churchill','lincoln','da vinci'], n:7 },
  { c:'essen', d:2, topic:'Nenne Süßigkeiten', items:['schokolade','gummibärchen','bonbon','lutscher','kaugummi','keks','praline','lakritz','marshmallow','toffee','riegel','smarties'], n:8 },
  { c:'natur', d:2, topic:'Nenne Naturkatastrophen', items:['erdbeben','vulkanausbruch','tsunami','hurrikan','tornado','überschwemmung','dürre','lawine','waldbrand','flut','sturm'], n:7 },
  { c:'aktuelles', d:2, topic:'Nenne große Tech-Erfindungen', items:['internet','smartphone','computer','rad','glühbirne','telefon','auto','flugzeug','dampfmaschine','druckpresse','elektrizität'], n:7 },
];

module.exports = { TF, EST, LISTS };
