/* =========================================================================
   NOVA QUIZ — extra content: True/False, Estimation, Top-Lists.
   TF:    { c, d, q, tf:true|false }
   EST:   { c, d, q, val:Number, unit:'' }
   LISTS: { c, d, topic, items:[accepted answers], n:targetCount, unit }
   ========================================================================= */
'use strict';

const TF = [
  { c:'allgemein', d:1, q:'Ein Dreieck hat drei Ecken.', tf:true },
  { c:'allgemein', d:1, q:'Die Sonne dreht sich um die Erde.', tf:false },
  { c:'allgemein', d:2, q:'Glas wird aus Sand hergestellt.', tf:true },
  { c:'allgemein', d:2, q:'Ein Kilometer hat 100 Meter.', tf:false },
  { c:'allgemein', d:1, q:'Wasser kocht bei 100 °C auf Meereshöhe.', tf:true },
  { c:'wissenschaft', d:2, q:'Schall breitet sich im Vakuum aus.', tf:false },
  { c:'wissenschaft', d:1, q:'Menschen haben fünf klassische Sinne.', tf:true },
  { c:'wissenschaft', d:3, q:'Diamant besteht aus reinem Kohlenstoff.', tf:true },
  { c:'wissenschaft', d:2, q:'Spinnen sind Insekten.', tf:false },
  { c:'wissenschaft', d:2, q:'Der Mensch nutzt nur 10 % seines Gehirns.', tf:false },
  { c:'wissenschaft', d:3, q:'Blut ist im Körper blau und wird rot an der Luft.', tf:false },
  { c:'natur', d:1, q:'Fische können ertrinken.', tf:false },
  { c:'natur', d:2, q:'Bananen wachsen an Bäumen.', tf:false },
  { c:'natur', d:2, q:'Ein Oktopus hat drei Herzen.', tf:true },
  { c:'natur', d:1, q:'Pinguine können fliegen.', tf:false },
  { c:'tiere', d:2, q:'Elefanten können nicht springen.', tf:true },
  { c:'tiere', d:2, q:'Eine Schnecke kann mehrere Jahre schlafen.', tf:true },
  { c:'tiere', d:1, q:'Kühe haben vier Mägen.', tf:true },
  { c:'tiere', d:3, q:'Haie sind Säugetiere.', tf:false },
  { c:'geografie', d:1, q:'Australien ist ein Land und ein Kontinent.', tf:true },
  { c:'geografie', d:2, q:'Der Nil fließt durch Ägypten.', tf:true },
  { c:'geografie', d:2, q:'Russland ist das größte Land der Erde.', tf:true },
  { c:'geografie', d:3, q:'Die Sahara ist die größte Wüste der Welt.', tf:false },
  { c:'geschichte', d:2, q:'Die Berliner Mauer fiel 1989.', tf:true },
  { c:'geschichte', d:2, q:'Die Pyramiden von Gizeh stehen in Mexiko.', tf:false },
  { c:'geschichte', d:3, q:'Der Zweite Weltkrieg endete 1945.', tf:true },
  { c:'weltraum', d:1, q:'Die Sonne ist ein Stern.', tf:true },
  { c:'weltraum', d:2, q:'Der Mars wird der "Rote Planet" genannt.', tf:true },
  { c:'weltraum', d:2, q:'Auf dem Mond gibt es Schwerkraft.', tf:true },
  { c:'weltraum', d:3, q:'Die Venus ist heißer als der Merkur.', tf:true },
  { c:'koerper', d:2, q:'Das Herz ist ein Muskel.', tf:true },
  { c:'koerper', d:2, q:'Erwachsene haben mehr Knochen als Babys.', tf:false },
  { c:'koerper', d:1, q:'Der Magen verdaut Nahrung.', tf:true },
  { c:'technik', d:1, q:'Eine SSD ist schneller als eine klassische Festplatte.', tf:true },
  { c:'technik', d:2, q:'WLAN überträgt Daten über Funk.', tf:true },
  { c:'technik', d:2, q:'HTML ist eine Programmiersprache zum Berechnen.', tf:false },
  { c:'sport', d:1, q:'Beim Tennis zählt man 15, 30, 40.', tf:true },
  { c:'sport', d:2, q:'Ein Fußballspiel dauert regulär 90 Minuten.', tf:true },
  { c:'sport', d:2, q:'Beim Basketball zählt ein Korb immer 3 Punkte.', tf:false },
  { c:'essen', d:1, q:'Honig wird von Bienen produziert.', tf:true },
  { c:'essen', d:2, q:'Tomaten sind botanisch gesehen Obst.', tf:true },
  { c:'essen', d:2, q:'Weiße Schokolade enthält Kakaobutter.', tf:true },
  { c:'musik', d:2, q:'Ein Klavier hat 88 Tasten.', tf:true },
  { c:'musik', d:2, q:'Eine Geige hat sechs Saiten.', tf:false },
  { c:'film', d:2, q:'Der Film "Titanic" wurde von James Cameron gedreht.', tf:true },
  { c:'gaming', d:2, q:'Mario ist eine Figur von Nintendo.', tf:true },
  { c:'gaming', d:2, q:'Minecraft wurde ursprünglich von Mojang entwickelt.', tf:true },
  { c:'mathe', d:1, q:'Eine gerade Zahl ist durch 2 teilbar.', tf:true },
  { c:'mathe', d:2, q:'Null ist eine Primzahl.', tf:false },
  { c:'mathe', d:2, q:'Ein Quadrat hat vier gleich lange Seiten.', tf:true },
  { c:'wirtschaft', d:2, q:'Der Euro ist die Währung mehrerer EU-Länder.', tf:true },
  { c:'wirtschaft', d:2, q:'Bitcoin ist eine physische Münze.', tf:false },
  { c:'aktuelles', d:2, q:'Die Olympischen Sommerspiele 2024 fanden in Paris statt.', tf:true },
  { c:'aktuelles', d:2, q:'Twitter wurde in "X" umbenannt.', tf:true },
  { c:'sprache', d:2, q:'"Lol" ist eine Abkürzung für lautes Lachen im Internet.', tf:true },
  { c:'mythologie', d:2, q:'Zeus ist der griechische Göttervater.', tf:true },
  { c:'mythologie', d:3, q:'Thor stammt aus der ägyptischen Mythologie.', tf:false },
  { c:'auto', d:2, q:'Tesla baut hauptsächlich Elektroautos.', tf:true },
  { c:'auto', d:2, q:'Ferrari ist eine deutsche Automarke.', tf:false },
  { c:'kunst', d:2, q:'Leonardo da Vinci malte die Mona Lisa.', tf:true },

  /* ===== EXPANSION: more True/False ===== */
  { c:'geografie', d:2, q:'Die Hauptstadt von Australien ist Sydney.', tf:false },
  { c:'geografie', d:1, q:'Afrika ist ein Kontinent.', tf:true },
  { c:'geografie', d:3, q:'Der Mount Everest ist der höchste Berg der Erde.', tf:true },
  { c:'geografie', d:2, q:'Es gibt mehr als 200 Länder auf der Welt.', tf:false },
  { c:'wissenschaft', d:2, q:'Gold ist ein chemisches Element.', tf:true },
  { c:'wissenschaft', d:3, q:'Ein Jahr auf der Venus ist kürzer als ein Tag dort.', tf:true },
  { c:'wissenschaft', d:1, q:'Eis ist gefrorenes Wasser.', tf:true },
  { c:'wissenschaft', d:2, q:'Der Mensch kann ohne Sauerstoff leben.', tf:false },
  { c:'tiere', d:2, q:'Ein Strauß ist der größte lebende Vogel.', tf:true },
  { c:'tiere', d:2, q:'Schmetterlinge schmecken mit den Füßen.', tf:true },
  { c:'tiere', d:3, q:'Ein Kolibri kann rückwärts fliegen.', tf:true },
  { c:'tiere', d:2, q:'Schildkröten haben Zähne.', tf:false },
  { c:'koerper', d:2, q:'Der Mensch hat zwei Nieren.', tf:true },
  { c:'koerper', d:3, q:'Niesen ist mit offenen Augen unmöglich.', tf:false },
  { c:'koerper', d:2, q:'Fingernägel wachsen schneller als Fußnägel.', tf:true },
  { c:'geschichte', d:2, q:'Die alten Ägypter bauten die Pyramiden.', tf:true },
  { c:'geschichte', d:3, q:'Albert Einstein erfand die Glühbirne.', tf:false },
  { c:'geschichte', d:2, q:'Die USA erklärten 1776 ihre Unabhängigkeit.', tf:true },
  { c:'sport', d:2, q:'Beim Boxen gibt es Runden.', tf:true },
  { c:'sport', d:3, q:'Ein Tennismatch kann unentschieden enden.', tf:false },
  { c:'sport', d:2, q:'Die Tour de France ist ein Radrennen.', tf:true },
  { c:'technik', d:2, q:'Ein QR-Code kann Informationen speichern.', tf:true },
  { c:'technik', d:2, q:'USB steht für "Universal Serial Bus".', tf:true },
  { c:'technik', d:3, q:'Die erste E-Mail wurde in den 1970ern verschickt.', tf:true },
  { c:'weltraum', d:2, q:'Die Erde ist der dritte Planet von der Sonne.', tf:true },
  { c:'weltraum', d:3, q:'Auf dem Mars gibt es flüssiges Wasser an der Oberfläche.', tf:false },
  { c:'weltraum', d:2, q:'Der Mond leuchtet aus eigener Kraft.', tf:false },
  { c:'essen', d:2, q:'Karotten sind gut für die Augen.', tf:true },
  { c:'essen', d:3, q:'Honig kann nicht verderben.', tf:true },
  { c:'essen', d:2, q:'Erdnüsse sind Nüsse.', tf:false },
  { c:'film', d:2, q:'Yoda kommt in Star Wars vor.', tf:true },
  { c:'gaming', d:2, q:'Tetris stammt ursprünglich aus Russland.', tf:true },
  { c:'gaming', d:2, q:'Pac-Man ist ein Rennspiel.', tf:false },
  { c:'mathe', d:2, q:'Die Summe der Innenwinkel eines Dreiecks ist 180°.', tf:true },
  { c:'mathe', d:2, q:'Jede Primzahl ist ungerade.', tf:false },
  { c:'mathe', d:3, q:'Pi ist eine irrationale Zahl.', tf:true },
  { c:'wirtschaft', d:2, q:'Amazon begann als Online-Buchhandlung.', tf:true },
  { c:'wirtschaft', d:3, q:'Der NASDAQ ist eine Börse.', tf:true },
  { c:'sprache', d:2, q:'Englisch ist die meistgesprochene Muttersprache der Welt.', tf:false },
  { c:'mythologie', d:2, q:'Herkules ist für seine Stärke bekannt.', tf:true },

  /* ===== EXPANSION: more True/False ===== */
  { c:'allgemein', d:2, q:'Ein Jahr hat 365 oder 366 Tage.', tf:true },
  { c:'allgemein', d:1, q:'Ein Quadrat hat fünf Ecken.', tf:false },
  { c:'allgemein', d:2, q:'Der Buchstabe "Y" ist ein Vokal im Deutschen.', tf:false },
  { c:'wissenschaft', d:2, q:'Licht ist schneller als Schall.', tf:true },
  { c:'wissenschaft', d:3, q:'Wasser besteht aus Wasserstoff und Sauerstoff.', tf:true },
  { c:'wissenschaft', d:2, q:'Ein Magnet hat einen Nord- und einen Südpol.', tf:true },
  { c:'wissenschaft', d:3, q:'Schokolade ist für Hunde ungefährlich.', tf:false },
  { c:'geografie', d:2, q:'Die Antarktis ist der trockenste Kontinent.', tf:true },
  { c:'geografie', d:2, q:'Vatikanstadt ist der kleinste Staat der Welt.', tf:true },
  { c:'geografie', d:3, q:'Istanbul ist die Hauptstadt der Türkei.', tf:false },
  { c:'geschichte', d:2, q:'Die Mona Lisa hängt im Louvre in Paris.', tf:true },
  { c:'geschichte', d:3, q:'Die Olympischen Spiele stammen aus dem antiken Griechenland.', tf:true },
  { c:'tiere', d:2, q:'Ein Pinguin ist ein Vogel.', tf:true },
  { c:'tiere', d:2, q:'Spinnen haben sechs Beine.', tf:false },
  { c:'tiere', d:3, q:'Krokodile können ihre Zunge nicht herausstrecken.', tf:true },
  { c:'koerper', d:2, q:'Der Mensch atmet Sauerstoff ein und Kohlendioxid aus.', tf:true },
  { c:'koerper', d:3, q:'Der Daumen hat drei Glieder wie die anderen Finger.', tf:false },
  { c:'weltraum', d:2, q:'Pluto gilt heute offiziell als Zwergplanet.', tf:true },
  { c:'weltraum', d:3, q:'Auf dem Mond gibt es keine Atmosphäre wie auf der Erde.', tf:true },
  { c:'sport', d:2, q:'Beim Schach gewinnt man durch "Schachmatt".', tf:true },
  { c:'sport', d:2, q:'Ein Basketballkorb hängt in 3,05 m Höhe.', tf:true },
  { c:'essen', d:2, q:'Sushi kommt ursprünglich aus China.', tf:false },
  { c:'essen', d:1, q:'Käse wird aus Milch hergestellt.', tf:true },
  { c:'gaming', d:2, q:'Lara Croft ist die Heldin von Tomb Raider.', tf:true },
  { c:'technik', d:2, q:'Ein Algorithmus ist eine Schritt-für-Schritt-Anleitung.', tf:true },
];

const EST = [
  { c:'geografie', d:2, q:'Wie hoch ist der Mount Everest (in Metern)?', val:8849, unit:'m' },
  { c:'geografie', d:2, q:'Wie viele Länder hat Afrika (ca.)?', val:54, unit:'' },
  { c:'geografie', d:3, q:'Wie lang ist der Nil (in km, ca.)?', val:6650, unit:'km' },
  { c:'geografie', d:2, q:'Wie viele Einwohner hat Deutschland (in Millionen, ca.)?', val:84, unit:'Mio.' },
  { c:'geografie', d:3, q:'Wie tief ist der Marianengraben (in Metern, ca.)?', val:11000, unit:'m' },
  { c:'weltraum', d:2, q:'Wie viele Monde hat der Mars?', val:2, unit:'' },
  { c:'weltraum', d:3, q:'Wie weit ist die Sonne von der Erde entfernt (in Mio. km, ca.)?', val:150, unit:'Mio. km' },
  { c:'weltraum', d:3, q:'Wie viele Erden würden ungefähr in die Sonne passen?', val:1300000, unit:'' },
  { c:'koerper', d:2, q:'Wie viele Knochen hat ein erwachsener Mensch?', val:206, unit:'' },
  { c:'koerper', d:3, q:'Wie oft schlägt ein menschliches Herz pro Tag (ca.)?', val:100000, unit:'' },
  { c:'koerper', d:2, q:'Wie viel Prozent des menschlichen Körpers besteht aus Wasser (ca.)?', val:60, unit:'%' },
  { c:'wissenschaft', d:2, q:'Bei wie viel °C gefriert Wasser?', val:0, unit:'°C' },
  { c:'wissenschaft', d:3, q:'Wie schnell ist Licht (in km/s, ca.)?', val:300000, unit:'km/s' },
  { c:'wissenschaft', d:2, q:'Wie viele Elemente hat das Periodensystem (ca.)?', val:118, unit:'' },
  { c:'geschichte', d:2, q:'In welchem Jahr fiel die Berliner Mauer?', val:1989, unit:'' },
  { c:'geschichte', d:2, q:'In welchem Jahr endete der Zweite Weltkrieg?', val:1945, unit:'' },
  { c:'geschichte', d:3, q:'In welchem Jahr sank die Titanic?', val:1912, unit:'' },
  { c:'sport', d:2, q:'Wie lang ist ein Marathon (in km, eine Nachkommastelle ok)?', val:42, unit:'km' },
  { c:'sport', d:2, q:'Wie viele Spieler hat eine Fußballmannschaft auf dem Feld?', val:11, unit:'' },
  { c:'sport', d:3, q:'Wie viele Teilnehmerländer hatte die Fußball-WM 2022?', val:32, unit:'' },
  { c:'natur', d:2, q:'Wie alt kann ein Mammutbaum werden (in Jahren, ca.)?', val:3000, unit:'Jahre' },
  { c:'tiere', d:2, q:'Wie schnell rennt ein Gepard (in km/h, ca.)?', val:110, unit:'km/h' },
  { c:'tiere', d:3, q:'Wie viele Herzen hat ein Regenwurm (ca.)?', val:5, unit:'' },
  { c:'tiere', d:2, q:'Wie lange ist ein Blauwal (in Metern, ca.)?', val:30, unit:'m' },
  { c:'technik', d:2, q:'Wie viele Bit hat ein Byte?', val:8, unit:'' },
  { c:'technik', d:3, q:'In welchem Jahr wurde das erste iPhone vorgestellt?', val:2007, unit:'' },
  { c:'essen', d:2, q:'Wie viele Kalorien hat ein Apfel (mittelgroß, ca.)?', val:95, unit:'kcal' },
  { c:'wirtschaft', d:3, q:'Wie viele Nullen hat eine Milliarde?', val:9, unit:'' },
  { c:'allgemein', d:1, q:'Wie viele Sekunden hat eine Minute?', val:60, unit:'' },
  { c:'allgemein', d:2, q:'Wie viele Knochen... äh, wie viele Tage hat ein Schaltjahr?', val:366, unit:'' },
  { c:'allgemein', d:2, q:'Wie viele Buchstaben hat das deutsche Alphabet (ohne Umlaute/ß)?', val:26, unit:'' },
  { c:'musik', d:2, q:'Wie viele Tasten hat ein Standard-Klavier?', val:88, unit:'' },
  { c:'film', d:3, q:'Wie viele "Star Wars"-Hauptfilme (Skywalker-Saga) gibt es?', val:9, unit:'' },
  { c:'weltraum', d:2, q:'Wie viele Planeten hat das Sonnensystem?', val:8, unit:'' },
  { c:'mathe', d:2, q:'Was ist 12 × 12?', val:144, unit:'' },
  { c:'mathe', d:3, q:'Was ergibt 2 hoch 10?', val:1024, unit:'' },
  { c:'geografie', d:3, q:'Wie viele Zeitzonen gibt es weltweit (ca.)?', val:24, unit:'' },
  { c:'koerper', d:3, q:'Wie viele Muskeln hat der menschliche Körper (ca.)?', val:640, unit:'' },
  { c:'geografie', d:2, q:'Wie viele Bundesländer hat Deutschland?', val:16, unit:'' },
  { c:'geografie', d:3, q:'Wie viele Mitgliedsstaaten hat die EU (Stand 2024)?', val:27, unit:'' },

  /* ===== EXPANSION: more Estimation ===== */
  { c:'geografie', d:2, q:'Wie viele Kontinente gibt es?', val:7, unit:'' },
  { c:'geografie', d:3, q:'Wie viele Länder gibt es ungefähr auf der Welt?', val:195, unit:'' },
  { c:'geografie', d:3, q:'Wie groß ist die Erde am Äquator im Umfang (in km, ca.)?', val:40075, unit:'km' },
  { c:'geografie', d:2, q:'Wie viele Einwohner hat die Erde (in Milliarden, ca.)?', val:8, unit:'Mrd.' },
  { c:'koerper', d:2, q:'Wie viele Zähne hat ein Erwachsener?', val:32, unit:'' },
  { c:'koerper', d:3, q:'Wie viele Liter Blut hat ein Erwachsener ungefähr?', val:5, unit:'l' },
  { c:'koerper', d:3, q:'Wie viele Chromosomenpaare hat der Mensch?', val:23, unit:'' },
  { c:'wissenschaft', d:2, q:'Bei wie viel °C kocht Wasser auf Meereshöhe?', val:100, unit:'°C' },
  { c:'wissenschaft', d:3, q:'Wie viele Beine hat eine Spinne?', val:8, unit:'' },
  { c:'tiere', d:2, q:'Wie viele Zähne hat ein erwachsener Hund ungefähr?', val:42, unit:'' },
  { c:'tiere', d:3, q:'Wie lange ist die Tragezeit eines Elefanten (in Monaten, ca.)?', val:22, unit:'Monate' },
  { c:'tiere', d:2, q:'Wie viele Eier legt ein Huhn etwa pro Jahr?', val:300, unit:'' },
  { c:'sport', d:2, q:'Wie viele Minuten dauert eine Halbzeit beim Fußball?', val:45, unit:'min' },
  { c:'sport', d:2, q:'Wie viele Spieler stehen beim Basketball pro Team auf dem Feld?', val:5, unit:'' },
  { c:'sport', d:3, q:'Wie viele olympische Goldmedaillen gewann Michael Phelps insgesamt?', val:23, unit:'' },
  { c:'geschichte', d:2, q:'In welchem Jahr begann der Erste Weltkrieg?', val:1914, unit:'' },
  { c:'geschichte', d:3, q:'In welchem Jahr landete der erste Mensch auf dem Mond?', val:1969, unit:'' },
  { c:'geschichte', d:2, q:'In welchem Jahr wurde Amerika von Kolumbus "entdeckt"?', val:1492, unit:'' },
  { c:'weltraum', d:2, q:'Wie viele Minuten braucht das Sonnenlicht bis zur Erde (ca.)?', val:8, unit:'min' },
  { c:'weltraum', d:3, q:'Wie viele bekannte Monde hat der Jupiter (ca.)?', val:95, unit:'' },
  { c:'technik', d:2, q:'Wie viele Megabyte hat ein Gigabyte?', val:1024, unit:'MB' },
  { c:'technik', d:3, q:'In welchem Jahr wurde Google gegründet?', val:1998, unit:'' },
  { c:'allgemein', d:1, q:'Wie viele Stunden hat ein Tag?', val:24, unit:'' },
  { c:'allgemein', d:1, q:'Wie viele Monate hat ein Jahr?', val:12, unit:'' },
  { c:'allgemein', d:2, q:'Wie viele Tasten hat eine Standard-PC-Tastatur (ca.)?', val:105, unit:'' },
  { c:'mathe', d:2, q:'Was ist 25 × 4?', val:100, unit:'' },
  { c:'mathe', d:3, q:'Wie viele Sekunden hat eine Stunde?', val:3600, unit:'' },
  { c:'essen', d:2, q:'Wie viele Gramm hat ein Kilogramm?', val:1000, unit:'g' },
  { c:'wirtschaft', d:3, q:'Wie viele Nullen hat eine Million?', val:6, unit:'' },
  { c:'kunst', d:3, q:'In welchem Jahrhundert lebte William Shakespeare (16.–17.)?', val:16, unit:'.Jh.' },

  /* ===== EXPANSION: more Estimation ===== */
  { c:'geografie', d:2, q:'Wie viele Sterne hat die Flagge der USA?', val:50, unit:'' },
  { c:'geografie', d:3, q:'Wie hoch ist der Eiffelturm (in Metern, ca.)?', val:330, unit:'m' },
  { c:'geografie', d:3, q:'Wie hoch ist die Freiheitsstatue mit Sockel (in Metern, ca.)?', val:93, unit:'m' },
  { c:'geografie', d:2, q:'Wie viele Großbuchstaben-Länder hat Südamerika (ca.)?', val:12, unit:'' },
  { c:'sport', d:2, q:'Wie viele Ringe hat das olympische Symbol?', val:5, unit:'' },
  { c:'sport', d:3, q:'Wie viele Bundesliga-Vereine gibt es in der 1. Liga?', val:18, unit:'' },
  { c:'sport', d:2, q:'Wie viele Punkte gibt ein Strafstoß-Tor im Fußball?', val:1, unit:'Tor' },
  { c:'weltraum', d:3, q:'Wie viele Sterne kann man mit bloßem Auge nachts grob sehen (ca.)?', val:2500, unit:'' },
  { c:'weltraum', d:2, q:'Wie lange dauert ein Tag auf der Erde (in Stunden)?', val:24, unit:'h' },
  { c:'koerper', d:2, q:'Wie viele Finger hat ein Mensch (beide Hände)?', val:10, unit:'' },
  { c:'koerper', d:3, q:'Wie viele Geschmacksrichtungen unterscheidet die Zunge grob?', val:5, unit:'' },
  { c:'tiere', d:2, q:'Wie viele Beine hat ein Tausendfüßler typischerweise (Dutzende bis hunderte, ca.)?', val:200, unit:'' },
  { c:'tiere', d:3, q:'Wie viele Zähne hat ein Hai etwa gleichzeitig im Maul (ca.)?', val:50, unit:'' },
  { c:'wissenschaft', d:3, q:'Wie viele Planeten im Sonnensystem haben Ringe?', val:4, unit:'' },
  { c:'wissenschaft', d:2, q:'Wie viele Aggregatzustände gibt es klassisch (fest/flüssig/gas)?', val:3, unit:'' },
  { c:'technik', d:3, q:'In welchem Jahr wurde YouTube gegründet?', val:2005, unit:'' },
  { c:'technik', d:3, q:'In welchem Jahr kam das erste iPhone (Wiederholung der Tech-Frage)?', val:2007, unit:'' },
  { c:'geschichte', d:3, q:'In welchem Jahr begann der Zweite Weltkrieg?', val:1939, unit:'' },
  { c:'geschichte', d:3, q:'In welchem Jahr wurde die Berliner Mauer gebaut?', val:1961, unit:'' },
  { c:'allgemein', d:2, q:'Wie viele Felder hat ein Schachbrett?', val:64, unit:'' },
  { c:'allgemein', d:2, q:'Wie viele Spielkarten hat ein französisches Blatt (mit Jokern)?', val:54, unit:'' },
  { c:'musik', d:3, q:'Wie viele Saiten hat eine Harfe typischerweise (ca.)?', val:47, unit:'' },
];

const LISTS = [
  { c:'weltraum', d:1, topic:'Nenne Planeten unseres Sonnensystems', items:['merkur','venus','erde','mars','jupiter','saturn','uranus','neptun'], n:8 },
  { c:'allgemein', d:1, topic:'Nenne die Farben des Regenbogens', items:['rot','orange','gelb','grün','blau','indigo','violett'], n:7 },
  { c:'geografie', d:1, topic:'Nenne die Kontinente', items:['europa','asien','afrika','nordamerika','südamerika','australien','ozeanien','antarktis','antarktika'], n:7 },
  { c:'allgemein', d:1, topic:'Nenne die Wochentage', items:['montag','dienstag','mittwoch','donnerstag','freitag','samstag','sonntag'], n:7 },
  { c:'allgemein', d:2, topic:'Nenne Monate des Jahres', items:['januar','februar','märz','april','mai','juni','juli','august','september','oktober','november','dezember'], n:8 },
  { c:'geografie', d:2, topic:'Nenne Nachbarländer Deutschlands', items:['frankreich','österreich','schweiz','polen','tschechien','dänemark','niederlande','belgien','luxemburg'], n:7 },
  { c:'geografie', d:3, topic:'Nenne deutsche Bundesländer', items:['bayern','baden-württemberg','hessen','niedersachsen','nordrhein-westfalen','nrw','rheinland-pfalz','saarland','sachsen','sachsen-anhalt','thüringen','brandenburg','mecklenburg-vorpommern','schleswig-holstein','berlin','hamburg','bremen'], n:8 },
  { c:'film', d:1, topic:'Nenne die Häuser in Harry Potter', items:['gryffindor','slytherin','hufflepuff','ravenclaw'], n:4 },
  { c:'musik', d:2, topic:'Nenne Mitglieder der Beatles', items:['john lennon','paul mccartney','george harrison','ringo starr','lennon','mccartney','harrison','starr'], n:4 },
  { c:'sport', d:1, topic:'Nenne die Farben der olympischen Ringe', items:['blau','gelb','schwarz','grün','rot'], n:5 },
  { c:'essen', d:1, topic:'Nenne beliebte Pizzabeläge', items:['käse','salami','schinken','pilze','champignons','peperoni','zwiebeln','paprika','ananas','tomaten','oliven','thunfisch','sardellen','rucola','spinat','hähnchen'], n:8 },
  { c:'essen', d:1, topic:'Nenne beliebte Obstsorten', items:['apfel','banane','orange','erdbeere','traube','weintraube','birne','kirsche','pfirsich','melone','ananas','mango','kiwi','zitrone','himbeere','blaubeere','pflaume'], n:8 },
  { c:'essen', d:1, topic:'Nenne beliebte Gemüsesorten', items:['karotte','möhre','tomate','gurke','kartoffel','zwiebel','paprika','brokkoli','salat','spinat','zucchini','aubergine','kohl','blumenkohl','erbse','bohne','mais'], n:8 },
  { c:'essen', d:2, topic:'Nenne beliebte Lebensmittel im Supermarkt', items:['milch','brot','eier','butter','käse','wurst','obst','gemüse','nudeln','reis','mehl','zucker','kaffee','tee','wasser','saft','joghurt','fleisch','fisch','schokolade','chips'], n:10 },
  { c:'essen', d:2, topic:'Nenne beliebte Eissorten', items:['vanille','schokolade','erdbeere','stracciatella','zitrone','haselnuss','pistazie','mango','cookie','karamell','joghurt','banane','kirsche'], n:8 },
  { c:'essen', d:2, topic:'Nenne beliebte Heißgetränke', items:['kaffee','tee','kakao','espresso','cappuccino','latte','glühwein','milchkaffee','grüner tee'], n:6 },
  { c:'natur', d:2, topic:'Nenne Planeten mit Ringen', items:['saturn','jupiter','uranus','neptun'], n:4 },
  { c:'sport', d:2, topic:'Nenne beliebte Ballsportarten', items:['fußball','basketball','handball','volleyball','tennis','tischtennis','golf','baseball','rugby','football','wasserball'], n:8 },
  { c:'sport', d:3, topic:'Nenne Länder, die Fußball-Weltmeister wurden', items:['brasilien','deutschland','italien','argentinien','frankreich','uruguay','england','spanien'], n:8 },
  { c:'film', d:2, topic:'Nenne Avengers (Marvel)', items:['iron man','captain america','thor','hulk','black widow','hawkeye','spider-man','black panther','doctor strange','ant-man','scarlet witch','vision','captain marvel','war machine','falcon'], n:8 },
  { c:'film', d:3, topic:'Nenne Star-Wars-Figuren', items:['luke skywalker','darth vader','yoda','han solo','leia','chewbacca','obi-wan','r2-d2','c-3po','kylo ren','rey','finn','palpatine','boba fett','anakin'], n:8 },
  { c:'wirtschaft', d:2, topic:'Nenne bekannte Tech-Unternehmen', items:['apple','google','microsoft','amazon','meta','facebook','samsung','tesla','nvidia','intel','ibm','sony','netflix','oracle'], n:8 },
  { c:'wirtschaft', d:2, topic:'Nenne bekannte Automarken', items:['mercedes','bmw','audi','volkswagen','vw','toyota','ford','ferrari','porsche','tesla','opel','honda','nissan','hyundai','renault','fiat','mazda','kia','volvo'], n:10 },
  { c:'wirtschaft', d:2, topic:'Nenne beliebte Social-Media-Apps', items:['instagram','tiktok','facebook','youtube','snapchat','x','twitter','whatsapp','telegram','reddit','pinterest','linkedin','discord','threads'], n:8 },
  { c:'wirtschaft', d:2, topic:'Nenne beliebte Streaming-Dienste', items:['netflix','disney+','disney plus','amazon prime','prime video','youtube','spotify','apple tv','hbo','max','paramount','dazn','sky','wow'], n:7 },
  { c:'wirtschaft', d:3, topic:'Nenne bekannte Fast-Food-Ketten', items:['mcdonalds','mcdonald’s','burger king','kfc','subway','dominos','pizza hut','starbucks','five guys','wendys','taco bell'], n:7 },
  { c:'gaming', d:2, topic:'Nenne beliebte Videospiele', items:['minecraft','fortnite','gta','call of duty','fifa','roblox','league of legends','valorant','the witcher','zelda','mario','pokemon','counter-strike','overwatch','among us','tetris'], n:8 },
  { c:'gaming', d:2, topic:'Nenne Spielkonsolen-Hersteller', items:['sony','microsoft','nintendo','sega','atari'], n:4 },
  { c:'gaming', d:3, topic:'Nenne Nintendo-Konsolen', items:['switch','wii','wii u','gamecube','n64','nintendo 64','snes','nes','gameboy','game boy','ds','3ds'], n:7 },
  { c:'geografie', d:2, topic:'Nenne die größten Länder der Welt (Fläche)', items:['russland','kanada','usa','china','brasilien','australien','indien','argentinien','kasachstan','algerien'], n:7 },
  { c:'geografie', d:3, topic:'Nenne die bevölkerungsreichsten Länder', items:['indien','china','usa','indonesien','pakistan','nigeria','brasilien','bangladesch','russland','mexiko'], n:7 },
  { c:'geografie', d:2, topic:'Nenne Ozeane der Erde', items:['pazifik','atlantik','indischer ozean','arktischer ozean','südlicher ozean','antarktischer ozean'], n:5 },
  { c:'geografie', d:3, topic:'Nenne europäische Hauptstädte', items:['berlin','paris','madrid','rom','london','wien','amsterdam','brüssel','lissabon','warschau','prag','budapest','athen','dublin','stockholm','oslo','kopenhagen','helsinki','bern'], n:10 },
  { c:'natur', d:2, topic:'Nenne Raubkatzen', items:['löwe','tiger','leopard','gepard','jaguar','puma','luchs','panther','schneeleopard'], n:6 },
  { c:'tiere', d:2, topic:'Nenne Haustiere', items:['hund','katze','hamster','kaninchen','hase','meerschweinchen','vogel','wellensittich','fisch','goldfisch','schildkröte','maus','ratte','pferd'], n:7 },
  { c:'tiere', d:2, topic:'Nenne Meerestiere', items:['hai','wal','delfin','delphin','oktopus','krake','qualle','seestern','krabbe','hummer','tintenfisch','seepferdchen','rochen','thunfisch','robbe'], n:8 },
  { c:'tiere', d:2, topic:'Nenne Vogelarten', items:['adler','spatz','taube','amsel','meise','specht','eule','falke','pinguin','flamingo','papagei','schwan','ente','gans','rabe','krähe','storch'], n:8 },
  { c:'koerper', d:2, topic:'Nenne die fünf menschlichen Sinne', items:['sehen','hören','riechen','schmecken','tasten','fühlen','gehör','geruch','geschmack','sicht'], n:5 },
  { c:'koerper', d:2, topic:'Nenne Organe des Menschen', items:['herz','lunge','leber','niere','magen','gehirn','haut','darm','milz','bauchspeicheldrüse','blase'], n:8 },
  { c:'mythologie', d:3, topic:'Nenne griechische Götter', items:['zeus','poseidon','hades','athene','apollon','ares','hermes','aphrodite','artemis','hera','demeter','dionysos','hephaistos'], n:8 },
  { c:'musik', d:2, topic:'Nenne Musikinstrumente', items:['gitarre','klavier','geige','schlagzeug','flöte','trompete','bass','saxophon','cello','harfe','klarinette','posaune','keyboard','akkordeon'], n:8 },
  { c:'musik', d:3, topic:'Nenne Musikgenres', items:['pop','rock','rap','hip hop','jazz','klassik','techno','house','metal','reggae','blues','country','schlager','electro','punk','soul'], n:8 },
  { c:'film', d:2, topic:'Nenne Disney-Filme', items:['der könig der löwen','aladdin','frozen','die eiskönigin','findet nemo','toy story','cinderella','arielle','dumbo','bambi','tarzan','mulan','vaiana','encanto','zoomania'], n:8 },
  { c:'film', d:3, topic:'Nenne Filmgenres', items:['action','komödie','horror','drama','science fiction','sci-fi','thriller','western','fantasy','romanze','animation','musical','krimi','abenteuer','dokumentation'], n:8 },
  { c:'sprache', d:2, topic:'Nenne Weltsprachen (meistgesprochen)', items:['englisch','chinesisch','mandarin','spanisch','hindi','arabisch','französisch','russisch','portugiesisch','bengalisch','deutsch','japanisch'], n:7 },
  { c:'kunst', d:3, topic:'Nenne berühmte Maler', items:['van gogh','picasso','da vinci','leonardo da vinci','monet','rembrandt','michelangelo','dalí','dali','warhol','klimt','vermeer','frida kahlo','munch'], n:7 },
  { c:'geschichte', d:3, topic:'Nenne antike Weltwunder', items:['pyramiden','hängende gärten','zeusstatue','artemistempel','mausoleum','koloss von rhodos','koloss','leuchtturm von alexandria','leuchtturm'], n:6 },
  { c:'allgemein', d:2, topic:'Nenne Schachfiguren', items:['könig','dame','turm','läufer','springer','bauer','pferd'], n:6 },
  { c:'allgemein', d:2, topic:'Nenne die Grundfarben (subtraktiv/Malen)', items:['rot','gelb','blau'], n:3 },
  { c:'natur', d:2, topic:'Nenne Wetterphänomene', items:['regen','schnee','hagel','sturm','gewitter','nebel','sonne','wind','blitz','donner','tornado','regenbogen','frost','tau'], n:8 },
  { c:'natur', d:2, topic:'Nenne Edelmetalle/Edelsteine', items:['gold','silber','platin','diamant','rubin','saphir','smaragd','bernstein','perle','topas','amethyst'], n:6 },
  { c:'sport', d:2, topic:'Nenne olympische Sportarten', items:['schwimmen','leichtathletik','turnen','fechten','rudern','radfahren','boxen','judo','tennis','basketball','volleyball','handball','reiten','segeln','gewichtheben'], n:8 },
  { c:'wirtschaft', d:3, topic:'Nenne Kryptowährungen', items:['bitcoin','ethereum','dogecoin','litecoin','ripple','cardano','solana','tether','bnb','shiba'], n:6 },
  { c:'aktuelles', d:2, topic:'Nenne KI-Chatbots / KI-Tools', items:['chatgpt','gemini','claude','copilot','grok','llama','midjourney','dall-e','bard'], n:6 },
  { c:'essen', d:2, topic:'Nenne Käsesorten', items:['gouda','edamer','emmentaler','mozzarella','parmesan','feta','camembert','brie','cheddar','gorgonzola','ricotta','frischkäse'], n:8 },
  { c:'essen', d:2, topic:'Nenne Nudelsorten', items:['spaghetti','penne','fusilli','farfalle','tagliatelle','lasagne','makkaroni','ravioli','tortellini','rigatoni','gnocchi'], n:7 },
  { c:'geografie', d:3, topic:'Nenne die größten Städte der Welt', items:['tokio','delhi','shanghai','são paulo','mexiko-stadt','kairo','mumbai','peking','new york','istanbul'], n:7 },
  { c:'welt', d:3, topic:'Nenne Inselstaaten', items:['japan','island','irland','kuba','madagaskar','sri lanka','neuseeland','philippinen','indonesien','malta','zypern','jamaika','fidschi'], n:7 },

  /* ===== EXPANSION: more Top-Lists ===== */
  { c:'essen', d:2, topic:'Nenne beliebte Fastfood-Gerichte', items:['burger','pommes','pizza','hotdog','döner','nuggets','wrap','sandwich','taco','currywurst','chicken'], n:7 },
  { c:'essen', d:2, topic:'Nenne Frühstücksklassiker', items:['brötchen','müsli','ei','rührei','spiegelei','marmelade','croissant','pancakes','toast','haferflocken','speck','joghurt','obst'], n:8 },
  { c:'essen', d:2, topic:'Nenne Getränke ohne Alkohol', items:['wasser','cola','limonade','saft','tee','kaffee','kakao','eistee','sprudel','smoothie','milch','fanta','sprite'], n:8 },
  { c:'essen', d:3, topic:'Nenne Gewürze', items:['salz','pfeffer','paprika','curry','zimt','kümmel','muskat','oregano','basilikum','thymian','chili','ingwer','knoblauch','vanille','safran'], n:8 },
  { c:'natur', d:2, topic:'Nenne Bäume', items:['eiche','buche','birke','tanne','fichte','kiefer','ahorn','linde','kastanie','weide','pappel','ulme','esche','platane'], n:8 },
  { c:'natur', d:2, topic:'Nenne Blumen', items:['rose','tulpe','sonnenblume','gänseblümchen','nelke','lilie','orchidee','veilchen','narzisse','margerite','flieder','mohn'], n:8 },
  { c:'tiere', d:2, topic:'Nenne Insekten', items:['biene','wespe','ameise','käfer','fliege','mücke','schmetterling','libelle','grille','heuschrecke','marienkäfer','hummel'], n:8 },
  { c:'tiere', d:2, topic:'Nenne Reptilien', items:['schlange','krokodil','eidechse','schildkröte','gecko','leguan','chamäleon','alligator','waran'], n:6 },
  { c:'tiere', d:3, topic:'Nenne Dinosaurier', items:['tyrannosaurus','t-rex','triceratops','velociraptor','brachiosaurus','stegosaurus','diplodocus','spinosaurus','pteranodon','ankylosaurus'], n:6 },
  { c:'sport', d:2, topic:'Nenne Wintersportarten', items:['ski','skifahren','snowboard','eishockey','eiskunstlauf','rodeln','bob','biathlon','langlauf','curling','skispringen','eisschnelllauf'], n:7 },
  { c:'sport', d:3, topic:'Nenne berühmte Fußballer', items:['messi','ronaldo','neymar','mbappé','müller','maradona','pelé','beckham','zidane','ronaldinho','lewandowski','kroos','haaland'], n:7 },
  { c:'sport', d:3, topic:'Nenne Formel-1-Weltmeister', items:['hamilton','schumacher','vettel','verstappen','alonso','senna','prost','rosberg','räikkönen','häkkinen','lauda'], n:6 },
  { c:'geografie', d:2, topic:'Nenne afrikanische Länder', items:['ägypten','nigeria','südafrika','kenia','marokko','algerien','ghana','äthiopien','tansania','tunesien','angola','kongo','senegal'], n:7 },
  { c:'geografie', d:2, topic:'Nenne asiatische Länder', items:['china','japan','indien','thailand','vietnam','südkorea','indonesien','philippinen','pakistan','türkei','iran','saudi-arabien','malaysia'], n:8 },
  { c:'geografie', d:2, topic:'Nenne europäische Länder', items:['deutschland','frankreich','italien','spanien','polen','niederlande','belgien','schweden','norwegen','griechenland','portugal','österreich','schweiz','irland','dänemark','finnland'], n:10 },
  { c:'geografie', d:3, topic:'Nenne Flüsse in Europa', items:['rhein','donau','elbe','seine','themse','wolga','po','rhone','loire','oder','main','mosel','tiber'], n:7 },
  { c:'geografie', d:3, topic:'Nenne Gebirge der Welt', items:['alpen','himalaya','anden','rocky mountains','pyrenäen','karpaten','ural','kaukasus','atlas','appalachen'], n:6 },
  { c:'film', d:2, topic:'Nenne Pixar-Filme', items:['toy story','findet nemo','cars','oben','wall-e','ratatouille','die unglaublichen','coco','soul','alles steht kopf','monster ag','findet dorie'], n:7 },
  { c:'film', d:3, topic:'Nenne Superhelden', items:['superman','batman','spider-man','iron man','hulk','thor','wonder woman','flash','captain america','aquaman','black panther','wolverine','deadpool'], n:8 },
  { c:'musik', d:3, topic:'Nenne berühmte Bands', items:['beatles','queen','rolling stones','abba','u2','coldplay','metallica','nirvana','ac/dc','led zeppelin','pink floyd','linkin park','imagine dragons'], n:7 },
  { c:'musik', d:3, topic:'Nenne berühmte Sänger/innen', items:['michael jackson','madonna','beyoncé','taylor swift','elvis','ed sheeran','rihanna','adele','bruno mars','justin bieber','lady gaga','drake','eminem'], n:8 },
  { c:'gaming', d:2, topic:'Nenne Pokémon', items:['pikachu','glumanda','schiggy','bisasam','evoli','enton','relaxo','mewtu','mew','rattfratz','taubsi','karpador','garados'], n:7 },
  { c:'gaming', d:3, topic:'Nenne Spielentwickler/Studios', items:['nintendo','rockstar','ubisoft','ea','electronic arts','activision','valve','mojang','cd projekt','epic games','blizzard','bethesda','sega','capcom'], n:7 },
  { c:'mythologie', d:3, topic:'Nenne nordische Götter', items:['odin','thor','loki','freya','baldur','heimdall','tyr','frigg','njörd','hel'], n:6 },
  { c:'mythologie', d:3, topic:'Nenne Fabelwesen', items:['drache','einhorn','phönix','zentaur','minotaurus','greif','meerjungfrau','elf','zwerg','troll','werwolf','vampir','kobold','sphinx'], n:8 },
  { c:'wirtschaft', d:2, topic:'Nenne Sportmarken', items:['nike','adidas','puma','under armour','reebok','new balance','asics','fila','jordan'], n:6 },
  { c:'wirtschaft', d:3, topic:'Nenne Modemarken/Luxus', items:['gucci','prada','chanel','louis vuitton','dior','versace','armani','hermès','rolex','burberry'], n:6 },
  { c:'koerper', d:2, topic:'Nenne Körperteile', items:['kopf','arm','bein','hand','fuß','finger','nase','ohr','auge','mund','knie','schulter','ellbogen','bauch','rücken'], n:8 },
  { c:'koerper', d:3, topic:'Nenne Knochen im Körper', items:['schädel','wirbelsäule','rippen','becken','oberschenkel','schienbein','wadenbein','oberarm','elle','speiche','schlüsselbein','kniescheibe'], n:6 },
  { c:'weltraum', d:2, topic:'Nenne Dinge im Weltall', items:['stern','planet','mond','komet','asteroid','galaxie','schwarzes loch','nebel','sonne','meteorit','satellit','rakete'], n:7 },
  { c:'sprache', d:2, topic:'Nenne Begrüßungen in anderen Sprachen', items:['hello','hola','bonjour','ciao','hallo','hi','salut','konnichiwa','namaste','aloha','privet','hej'], n:7 },
  { c:'allgemein', d:2, topic:'Nenne Planeten und Zwergplaneten', items:['merkur','venus','erde','mars','jupiter','saturn','uranus','neptun','pluto','ceres','eris'], n:8 },
  { c:'allgemein', d:2, topic:'Nenne Jahreszeiten', items:['frühling','sommer','herbst','winter'], n:4 },
  { c:'allgemein', d:2, topic:'Nenne Himmelsrichtungen', items:['norden','osten','süden','westen','nordosten','südosten','südwesten','nordwesten'], n:4 },
  { c:'kunst', d:3, topic:'Nenne berühmte Schriftsteller', items:['goethe','schiller','shakespeare','kafka','hemingway','tolkien','rowling','king','dostojewski','hesse','brecht','mann','grass'], n:7 },
  { c:'geschichte', d:3, topic:'Nenne historische Persönlichkeiten', items:['napoleon','cäsar','kleopatra','einstein','newton','gandhi','luther','columbus','alexander der große','churchill','lincoln','da vinci'], n:7 },
  { c:'essen', d:2, topic:'Nenne Süßigkeiten', items:['schokolade','gummibärchen','bonbon','lutscher','kaugummi','keks','praline','lakritz','marshmallow','toffee','riegel','smarties'], n:8 },
  { c:'natur', d:2, topic:'Nenne Naturkatastrophen', items:['erdbeben','vulkanausbruch','tsunami','hurrikan','tornado','überschwemmung','dürre','lawine','waldbrand','flut','sturm'], n:7 },
  { c:'aktuelles', d:2, topic:'Nenne große Tech-Erfindungen', items:['internet','smartphone','computer','rad','glühbirne','telefon','auto','flugzeug','dampfmaschine','druckpresse','elektrizität'], n:7 },
];

/* ===== EMOJI puzzles (guess from emojis) — answered like multiple choice ===== */
const EMOJI = [
  { c:'film', d:1, emoji:'🦁👑', q:'Welcher Film?', a:['Tarzan','Der König der Löwen','Madagascar','Dschungelbuch'], k:1 },
  { c:'film', d:1, emoji:'❄️👑', q:'Welcher Film?', a:['Die Eiskönigin','Cinderella','Rapunzel','Vaiana'], k:0 },
  { c:'film', d:1, emoji:'🕷️🧑', q:'Welcher Superheld?', a:['Batman','Spider-Man','Ant-Man','Iron Man'], k:1 },
  { c:'film', d:2, emoji:'🐠🔍', q:'Welcher Pixar-Film?', a:['Findet Nemo','Cars','Oben','Coco'], k:0 },
  { c:'film', d:2, emoji:'🚢🧊💔', q:'Welcher Film?', a:['Poseidon','Titanic','Pearl Harbor','Aquaman'], k:1 },
  { c:'film', d:2, emoji:'🦖🏞️', q:'Welcher Film?', a:['King Kong','Jurassic Park','Godzilla','Avatar'], k:1 },
  { c:'film', d:2, emoji:'⚡🧙', q:'Welche Filmreihe?', a:['Der Hobbit','Harry Potter','Merlin','Narnia'], k:1 },
  { c:'film', d:3, emoji:'🧙‍♂️💍🌋', q:'Welche Filmreihe?', a:['Harry Potter','Der Herr der Ringe','Game of Thrones','Eragon'], k:1 },
  { c:'film', d:2, emoji:'🤠🚀🧸', q:'Welcher Pixar-Film?', a:['Toy Story','Cars','Wall-E','Up'], k:0 },
  { c:'film', d:3, emoji:'🐀👨‍🍳', q:'Welcher Pixar-Film?', a:['Bee Movie','Ratatouille','Chicken Run','Madagascar'], k:1 },
  { c:'film', d:2, emoji:'👻🚫🔫', q:'Welcher Film?', a:['Casper','Ghostbusters','Beetlejuice','Poltergeist'], k:1 },
  { c:'film', d:1, emoji:'🦇🦸', q:'Welcher Superheld?', a:['Superman','Batman','Robin','Joker'], k:1 },
  { c:'film', d:3, emoji:'👽📞🏠', q:'Welcher Film?', a:['Alien','E.T.','Arrival','Signs'], k:1 },
  { c:'film', d:2, emoji:'🤖❤️🌱', q:'Welcher Pixar-Film?', a:['Wall-E','Big Hero 6','Transformers','Iron Giant'], k:0 },
  { c:'film', d:3, emoji:'🟦🧑🏹🌳', q:'Welcher Film?', a:['Shrek','Avatar','Smurfs','Brave'], k:1 },
  { c:'film', d:2, emoji:'🏴‍☠️⚓🦜', q:'Welche Filmreihe?', a:['Peter Pan','Fluch der Karibik','Hook','Tintin'], k:1 },
  { c:'film', d:3, emoji:'🧠😀😢😡', q:'Welcher Pixar-Film?', a:['Soul','Alles steht Kopf','Coco','Luca'], k:1 },
  { c:'film', d:2, emoji:'🦈🌊😱', q:'Welcher Film?', a:['Der weiße Hai','Findet Nemo','Aquaman','Meg'], k:0 },
  { c:'gaming', d:2, emoji:'🍄👨🟥', q:'Welches Game?', a:['Sonic','Super Mario','Crash','Rayman'], k:1 },
  { c:'gaming', d:2, emoji:'⛏️🟩🧟', q:'Welches Game?', a:['Roblox','Minecraft','Terraria','Fortnite'], k:1 },
  { c:'gaming', d:3, emoji:'🗡️🛡️🧝', q:'Welche Spielreihe?', a:['Zelda','Skyrim','Dark Souls','Witcher'], k:0 },
  { c:'gaming', d:1, emoji:'🟡👻👻', q:'Welcher Arcade-Klassiker?', a:['Tetris','Pac-Man','Snake','Frogger'], k:1 },
  { c:'essen', d:1, emoji:'🍅🧀🍕', q:'Welches Gericht?', a:['Lasagne','Pizza','Pasta','Burger'], k:1 },
  { c:'essen', d:1, emoji:'🍔🍟', q:'Welches Essen?', a:['Hotdog','Fast Food / Burger-Menü','Döner','Sandwich'], k:1 },
  { c:'essen', d:2, emoji:'🍣🍙🥢', q:'Welche Küche?', a:['Chinesisch','Japanisch (Sushi)','Thai','Koreanisch'], k:1 },
  { c:'tiere', d:1, emoji:'🦒', q:'Welches Tier?', a:['Zebra','Giraffe','Lama','Pferd'], k:1 },
  { c:'tiere', d:1, emoji:'🐙', q:'Welches Tier?', a:['Krake','Qualle','Tintenfisch','Seestern'], k:0 },
  { c:'tiere', d:2, emoji:'🦓', q:'Welches Tier?', a:['Pferd','Zebra','Esel','Gnu'], k:1 },
  { c:'natur', d:1, emoji:'🌈', q:'Was ist das?', a:['Sonne','Regenbogen','Wolke','Blitz'], k:1 },
  { c:'natur', d:2, emoji:'🌋', q:'Was ist das?', a:['Berg','Vulkan','Insel','Geysir'], k:1 },
  { c:'weltraum', d:1, emoji:'🚀🌕', q:'Was passiert?', a:['Mondlandung / Raumfahrt','Sonnenfinsternis','Urknall','Meteor'], k:0 },
  { c:'weltraum', d:2, emoji:'🪐', q:'Welcher Planet (Symbol)?', a:['Jupiter','Saturn','Uranus','Mars'], k:1 },
  { c:'sport', d:1, emoji:'⚽🥅', q:'Welche Sportart?', a:['Handball','Fußball','Rugby','Hockey'], k:1 },
  { c:'sport', d:2, emoji:'🏀🔥', q:'Welche Sportart?', a:['Volleyball','Basketball','Handball','Tennis'], k:1 },
  { c:'sport', d:2, emoji:'🏎️🏁', q:'Welcher Sport?', a:['Rallye','Formel 1','MotoGP','NASCAR'], k:1 },
  { c:'musik', d:2, emoji:'🎸🤘', q:'Welches Genre?', a:['Jazz','Rock','Klassik','Reggae'], k:1 },
  { c:'musik', d:2, emoji:'🎤👑', q:'Wer ist der "King of Pop"?', a:['Elvis','Michael Jackson','Prince','Drake'], k:1 },
  { c:'geografie', d:2, emoji:'🗼🥖🇫🇷', q:'Welches Land?', a:['Italien','Frankreich','Spanien','Belgien'], k:1 },
  { c:'geografie', d:2, emoji:'🍕🍝🛵', q:'Welches Land?', a:['Italien','Griechenland','Spanien','Portugal'], k:0 },
  { c:'geografie', d:3, emoji:'🗽🍔🦅', q:'Welches Land?', a:['Kanada','USA','Australien','England'], k:1 },
  { c:'geografie', d:2, emoji:'🐨🦘', q:'Welches Land?', a:['Neuseeland','Australien','Südafrika','Brasilien'], k:1 },
  { c:'aktuelles', d:2, emoji:'🤖💬', q:'Was ist das?', a:['Suchmaschine','KI-Chatbot','Videospiel','App-Store'], k:1 },
  { c:'mythologie', d:2, emoji:'⚡🧔👑', q:'Welcher Gott?', a:['Hades','Zeus','Poseidon','Ares'], k:1 },
  { c:'kunst', d:3, emoji:'👩🖼️🇫🇷', q:'Welches Gemälde?', a:['Die Sternennacht','Mona Lisa','Der Schrei','Guernica'], k:1 },

  /* ===== EXPANSION: more Emoji puzzles ===== */
  { c:'film', d:2, emoji:'🕶️🟢💊', q:'Welcher Film?', a:['Tron','Matrix','Inception','Blade Runner'], k:1 },
  { c:'film', d:2, emoji:'🤖🔫🕶️', q:'Welche Filmreihe?', a:['RoboCop','Terminator','I Robot','Transformers'], k:1 },
  { c:'film', d:3, emoji:'🐼🥋', q:'Welcher Film?', a:['Kung Fu Panda','Po','Karate Kid','Mulan'], k:0 },
  { c:'film', d:2, emoji:'🚗⚡👀', q:'Welcher Pixar-Film?', a:['Cars','Turbo','Ralph','Speed'], k:0 },
  { c:'film', d:3, emoji:'🤡🎈🤡', q:'Welcher Horrorfilm?', a:['Joker','Es','Saw','Annabelle'], k:1 },
  { c:'film', d:2, emoji:'🦍🏙️✈️', q:'Welcher Film?', a:['Godzilla','King Kong','Rampage','Mighty Joe'], k:1 },
  { c:'film', d:2, emoji:'🧚✨🏴‍☠️', q:'Welche Figur?', a:['Peter Pan','Aladdin','Pinocchio','Robin Hood'], k:0 },
  { c:'film', d:3, emoji:'🐸👸💋', q:'Welcher Disney-Film?', a:['Cinderella','Küss den Frosch','Arielle','Rapunzel'], k:1 },
  { c:'film', d:2, emoji:'🦷🧚💰', q:'Welche Figur?', a:['Zahnfee','Sandmann','Osterhase','Nikolaus'], k:0 },
  { c:'film', d:3, emoji:'🧛🦇🩸', q:'Welche Figur?', a:['Frankenstein','Dracula','Werwolf','Zombie'], k:1 },
  { c:'gaming', d:2, emoji:'🟦🟨🟥🧱', q:'Welches Game?', a:['Tetris','Minecraft','Lego','Roblox'], k:0 },
  { c:'gaming', d:2, emoji:'🍌🦍', q:'Welche Spielfigur?', a:['Diddy Kong','Donkey Kong','King K. Rool','Crash'], k:1 },
  { c:'gaming', d:3, emoji:'🔵💍💨', q:'Welche Spielfigur?', a:['Mega Man','Sonic','Rayman','Kirby'], k:1 },
  { c:'tiere', d:1, emoji:'🦏', q:'Welches Tier?', a:['Nilpferd','Nashorn','Elefant','Büffel'], k:1 },
  { c:'tiere', d:1, emoji:'🦉', q:'Welches Tier?', a:['Adler','Eule','Falke','Rabe'], k:1 },
  { c:'tiere', d:2, emoji:'🦔', q:'Welches Tier?', a:['Igel','Stachelschwein','Maulwurf','Biber'], k:0 },
  { c:'tiere', d:2, emoji:'🦦', q:'Welches Tier?', a:['Biber','Otter','Robbe','Marder'], k:1 },
  { c:'tiere', d:1, emoji:'🦩', q:'Welches Tier?', a:['Storch','Flamingo','Reiher','Pelikan'], k:1 },
  { c:'tiere', d:2, emoji:'🦫', q:'Welches Tier?', a:['Biber','Ratte','Hamster','Eichhörnchen'], k:0 },
  { c:'essen', d:1, emoji:'🍩', q:'Was ist das?', a:['Bagel','Donut','Brezel','Keks'], k:1 },
  { c:'essen', d:1, emoji:'🌮', q:'Was ist das?', a:['Burrito','Taco','Wrap','Quesadilla'], k:1 },
  { c:'essen', d:2, emoji:'🥐', q:'Was ist das?', a:['Brezel','Croissant','Bagel','Baguette'], k:1 },
  { c:'essen', d:1, emoji:'🍿', q:'Was ist das?', a:['Chips','Popcorn','Cornflakes','Müsli'], k:1 },
  { c:'essen', d:2, emoji:'🥨', q:'Was ist das?', a:['Brezel','Croissant','Donut','Bagel'], k:0 },
  { c:'essen', d:2, emoji:'🧇', q:'Was ist das?', a:['Pfannkuchen','Waffel','Toast','Keks'], k:1 },
  { c:'geografie', d:2, emoji:'🗼🍣🎌', q:'Welches Land?', a:['China','Japan','Korea','Thailand'], k:1 },
  { c:'geografie', d:2, emoji:'🐘🛕🍛', q:'Welches Land?', a:['Thailand','Indien','Vietnam','Nepal'], k:1 },
  { c:'geografie', d:3, emoji:'🦁🌍🥁', q:'Welcher Kontinent?', a:['Asien','Afrika','Südamerika','Australien'], k:1 },
  { c:'geografie', d:2, emoji:'🍺🥨🏔️', q:'Welches Land?', a:['Österreich','Deutschland','Schweiz','Belgien'], k:1 },
  { c:'geografie', d:3, emoji:'💃🐂🥘', q:'Welches Land?', a:['Italien','Spanien','Portugal','Mexiko'], k:1 },
  { c:'sport', d:1, emoji:'🥊🥊', q:'Welche Sportart?', a:['Ringen','Boxen','Judo','Karate'], k:1 },
  { c:'sport', d:2, emoji:'🎳', q:'Welche Sportart?', a:['Bowling','Billard','Curling','Boccia'], k:0 },
  { c:'sport', d:2, emoji:'🏹🎯', q:'Welche Sportart?', a:['Dart','Bogenschießen','Speerwurf','Schießen'], k:1 },
  { c:'sport', d:2, emoji:'🏓', q:'Welche Sportart?', a:['Tennis','Tischtennis','Badminton','Squash'], k:1 },
  { c:'sport', d:2, emoji:'⛳🏌️', q:'Welche Sportart?', a:['Hockey','Golf','Cricket','Polo'], k:1 },
  { c:'natur', d:2, emoji:'🌪️', q:'Was ist das?', a:['Hurrikan','Tornado','Gewitter','Blizzard'], k:1 },
  { c:'natur', d:1, emoji:'⛄❄️', q:'Welche Jahreszeit?', a:['Herbst','Winter','Frühling','Sommer'], k:1 },
  { c:'natur', d:2, emoji:'🍂🍁', q:'Welche Jahreszeit?', a:['Frühling','Herbst','Sommer','Winter'], k:1 },
  { c:'weltraum', d:2, emoji:'☄️', q:'Was ist das?', a:['Stern','Komet','Satellit','Mond'], k:1 },
  { c:'weltraum', d:1, emoji:'👨‍🚀', q:'Was ist das?', a:['Pilot','Astronaut','Taucher','Soldat'], k:1 },
  { c:'musik', d:2, emoji:'🎹🎼', q:'Welches Instrument?', a:['Gitarre','Klavier','Geige','Harfe'], k:1 },
  { c:'musik', d:2, emoji:'🎻', q:'Welches Instrument?', a:['Cello','Geige','Bratsche','Kontrabass'], k:1 },
  { c:'musik', d:3, emoji:'🎷', q:'Welches Instrument?', a:['Trompete','Saxophon','Klarinette','Posaune'], k:1 },
  { c:'allgemein', d:1, emoji:'🚒👨‍🚒', q:'Welcher Beruf?', a:['Polizist','Feuerwehrmann','Arzt','Pilot'], k:1 },
  { c:'allgemein', d:1, emoji:'👨‍⚕️💉', q:'Welcher Beruf?', a:['Arzt','Lehrer','Koch','Anwalt'], k:0 },
  { c:'allgemein', d:2, emoji:'👮🚓', q:'Welcher Beruf?', a:['Feuerwehr','Polizist','Soldat','Wachmann'], k:1 },
  { c:'aktuelles', d:2, emoji:'📱🍏', q:'Welche Marke?', a:['Samsung','Apple','Huawei','Nokia'], k:1 },
  { c:'aktuelles', d:2, emoji:'🚗⚡🔋', q:'Welche Marke?', a:['Toyota','Tesla','BMW','Ford'], k:1 },
  { c:'mythologie', d:2, emoji:'🔱🌊', q:'Welcher Gott?', a:['Zeus','Poseidon','Hades','Apollon'], k:1 },
  { c:'mythologie', d:3, emoji:'🏹☀️', q:'Welcher Gott?', a:['Ares','Apollon','Hermes','Hephaistos'], k:1 },
];

/* ===== VIDEO questions (embedded YouTube) — answered like multiple choice =====
   yt = YouTube video id. IDs recherchiert & verifiziert (meistgesehene/-gelikte
   offizielle Videos via Wikipedia + YouTube-Suche). Frei austauschbar. */
const VIDEO = [
  /* --- "Welcher Song ist das?" --- */
  { c:'musik', d:1, yt:'kJQP7kiw5Fk', q:'Welcher Song ist das?', a:['Bailando','Despacito','Macarena','Vivir Mi Vida'], k:1 },
  { c:'musik', d:1, yt:'RgKAFK5djSk', q:'Welcher Song ist das (Fast & Furious)?', a:['Happier','See You Again','Sugar','7 Years'], k:1 },
  { c:'musik', d:1, yt:'JGwWNGJdvx8', q:'Welcher Song ist das?', a:['Perfect','Shape of You','Photograph','Galway Girl'], k:1 },
  { c:'musik', d:1, yt:'9bZkp7q19f0', q:'Welcher virale Hit ist das?', a:['Harlem Shake','Gangnam Style','Gentleman','Macarena'], k:1 },
  { c:'musik', d:2, yt:'OPf0YbXqDm0', q:'Wie heißt dieser Funk-Hit?', a:['24K Magic','Uptown Funk','Treasure','Finesse'], k:1 },
  { c:'musik', d:2, yt:'hT_nvWreIhg', q:'Welcher Song ist das?', a:['Apologize','Counting Stars','Secrets','Good Life'], k:1 },
  { c:'musik', d:2, yt:'09R8_2nJtjg', q:'Welcher Maroon-5-Song ist das?', a:['Sugar','Maps','Animals','Memories'], k:0 },
  { c:'musik', d:2, yt:'CevxZvSJLk8', q:'Welcher Katy-Perry-Song ist das?', a:['Firework','Roar','Dark Horse','Hot n Cold'], k:1 },
  { c:'musik', d:3, yt:'0KSOMA3QBU0', q:'Welcher Katy-Perry-Song ist das?', a:['Dark Horse','Roar','Firework','Bon Appétit'], k:0 },
  { c:'musik', d:1, yt:'2Vv-BfVoq4g', q:'Welcher Ed-Sheeran-Song ist das?', a:['Perfect','Shape of You','Happier','Photograph'], k:0 },
  { c:'musik', d:1, yt:'fRh_vgS2dFE', q:'Welcher Justin-Bieber-Song ist das?', a:['Sorry','Love Yourself','What Do You Mean','Baby'], k:0 },
  { c:'musik', d:2, yt:'RBumgq5yVrA', q:'Welcher Song ist das?', a:['Let Her Go','Say Something','Hallelujah','Photograph'], k:0 },
  { c:'musik', d:2, yt:'aJOTlE1K90k', q:'Welcher Maroon-5-Song ist das?', a:['Sugar','Girls Like You','Memories','Maps'], k:1 },
  { c:'musik', d:2, yt:'lp-EO5I60KA', q:'Welcher Ed-Sheeran-Song ist das?', a:['Perfect','Thinking Out Loud','Photograph','Shape of You'], k:1 },
  { c:'musik', d:1, yt:'gdZLi9oWNZg', q:'Welcher BTS-Song ist das?', a:['Butter','Dynamite','Boy with Luv','DNA'], k:1 },
  { c:'musik', d:2, yt:'60ItHLz5WEA', q:'Welcher Alan-Walker-Song ist das?', a:['Alone','Faded','Sing Me to Sleep','The Spectre'], k:1 },
  { c:'musik', d:3, yt:'XsX3ATc3FbA', q:'Welcher BTS-Song ist das?', a:['Dynamite','Boy with Luv','Butter','Fake Love'], k:1 },
  { c:'musik', d:2, yt:'V1Pl8CzNzCw', q:'Welcher Billie-Eilish-Song ist das?', a:['Lovely','Bad Guy','Ocean Eyes','Bury a Friend'], k:0 },
  { c:'musik', d:2, yt:'KQ6zr6kCPj8', q:'Welcher Party-Hit ist das?', a:['Sexy and I Know It','Party Rock Anthem','Gangnam Style','Macarena'], k:1 },
  { c:'musik', d:1, yt:'k85mRPqvMbE', q:'Welcher Crazy-Frog-Hit ist das?', a:['Axel F','Cotton Eye Joe','Popcorn','Macarena'], k:0 },
  { c:'musik', d:1, yt:'4NRXx6U8ABQ', q:'Welcher The-Weeknd-Song ist das?', a:['Save Your Tears','Blinding Lights','Starboy','The Hills'], k:1 },
  { c:'musik', d:1, yt:'dQw4w9WgXcQ', q:'Welcher Internet-Klassiker ist das?', a:['Take On Me','Never Gonna Give You Up','Africa','Tainted Love'], k:1 },
  { c:'musik', d:2, yt:'hTWKbfoikeg', q:'Welcher Nirvana-Song ist das?', a:['Come As You Are','Smells Like Teen Spirit','In Bloom','Lithium'], k:1 },
  { c:'musik', d:1, yt:'DyDfgMOUjCI', q:'Welcher Billie-Eilish-Song ist das?', a:['bad guy','lovely','Therefore I Am','Happier Than Ever'], k:0 },
  { c:'musik', d:2, yt:'IHNzOHi8sJs', q:'Welcher BLACKPINK-Song ist das?', a:['Kill This Love','DDU-DU DDU-DU','How You Like That','Boombayah'], k:1 },
  { c:'film', d:1, yt:'XqZsoesa55w', q:'Welches Kinderlied ist das?', a:['Baby Shark','Wheels on the Bus','Johny Johny','Old MacDonald'], k:0 },
  { c:'film', d:1, yt:'e_04ZrNroTo', q:'Welches Kinderlied ist das?', a:['Baby Shark','Wheels on the Bus','Old MacDonald','Twinkle Twinkle'], k:1 },
  { c:'musik', d:2, yt:'fJ9rUzIMcZQ', q:'Welcher Queen-Klassiker ist das?', a:['We Will Rock You','Bohemian Rhapsody','Somebody to Love','Don’t Stop Me Now'], k:1 },
  { c:'musik', d:2, yt:'Zi_XLOBDo_Y', q:'Welcher Michael-Jackson-Song ist das?', a:['Beat It','Billie Jean','Thriller','Smooth Criminal'], k:1 },
  { c:'musik', d:2, yt:'7YuAzR2XVAM', q:'Welcher Eminem-Song ist das?', a:['Lose Yourself','Without Me','The Real Slim Shady','Stan'], k:0 },
  { c:'musik', d:1, yt:'TUVcZfQe-Kw', q:'Welcher Dua-Lipa-Song ist das?', a:['Levitating','Don’t Start Now','New Rules','Physical'], k:0 },
  { c:'musik', d:2, yt:'djV11Xbc914', q:'Welcher 80er-Hit ist das?', a:['Take On Me','Africa','Sweet Dreams','Tainted Love'], k:0 },
  { c:'musik', d:3, yt:'L_jWHffIx5E', q:'Welcher Shrek-Klassiker ist das?', a:['All Star','I’m a Believer','Walkin’ on the Sun','Then the Morning Comes'], k:0 },
  { c:'musik', d:1, yt:'ZbZSe6N_BXs', q:'Welcher Pharrell-Hit ist das?', a:['Happy','Get Lucky','Freedom','Blurred Lines'], k:0 },
  { c:'musik', d:2, yt:'8UVNT4wvIGY', q:'Welcher Gotye-Song ist das?', a:['Somebody That I Used to Know','Hearts a Mess','Eyes Wide Open','Save Me'], k:0 },
  { c:'musik', d:2, yt:'qrO4YZeyl0I', q:'Welcher Lady-Gaga-Song ist das?', a:['Poker Face','Bad Romance','Just Dance','Telephone'], k:1 },
  { c:'musik', d:1, yt:'7wtfhZwyrcc', q:'Welcher Imagine-Dragons-Song ist das?', a:['Believer','Thunder','Radioactive','Demons'], k:0 },
  { c:'musik', d:2, yt:'pRpeEdMmmQ0', q:'Welcher Shakira-WM-Song ist das?', a:['Hips Don’t Lie','Waka Waka','Whenever, Wherever','Try Everything'], k:1 },
  { c:'musik', d:2, yt:'IcrbM1l_BoI', q:'Welcher Avicii-Hit ist das?', a:['Wake Me Up','Levels','Hey Brother','Waiting for Love'], k:0 },
  { c:'musik', d:3, yt:'btPJPFnesV4', q:'Welcher Rocky-Song ist das?', a:['Eye of the Tiger','The Final Countdown','Born to Run','Living on a Prayer'], k:0 },
  { c:'musik', d:3, yt:'1w7OgIMMRc4', q:'Welcher Guns-N’-Roses-Song ist das?', a:['November Rain','Sweet Child O’ Mine','Paradise City','Welcome to the Jungle'], k:1 },
  { c:'musik', d:2, yt:'QK8mJJJvaes', q:'Welcher Macklemore-Song ist das?', a:['Thrift Shop','Can’t Hold Us','Same Love','Downtown'], k:0 },
  { c:'musik', d:1, yt:'450p7goxZqg', q:'Welcher John-Legend-Song ist das?', a:['All of Me','Ordinary People','Love Me Now','Stay'], k:0 },
  { c:'musik', d:2, yt:'r7qovpFAGrQ', q:'Welcher Lil-Nas-X-Song ist das?', a:['Old Town Road','Panini','Montero','Industry Baby'], k:0 },
  { c:'musik', d:3, yt:'2vjPBrBU-TM', q:'Welcher Sia-Song ist das?', a:['Chandelier','Cheap Thrills','Elastic Heart','The Greatest'], k:0 },
  { c:'musik', d:1, yt:'nfWlot6h_JM', q:'Welcher Taylor-Swift-Song ist das?', a:['Blank Space','Shake It Off','Bad Blood','Style'], k:1 },
  { c:'musik', d:1, yt:'YQHsXMglC9A', q:'Welcher Adele-Song ist das?', a:['Hello','Someone Like You','Rolling in the Deep','Easy on Me'], k:0 },
  { c:'musik', d:2, yt:'dvgZkm1xWPE', q:'Welcher Coldplay-Song ist das?', a:['Yellow','Viva la Vida','Paradise','Fix You'], k:1 },

  /* --- "Welcher Interpret ist das?" (gleiche Clips, andere Frage) --- */
  { c:'musik', d:2, yt:'kJQP7kiw5Fk', q:'Welcher Interpret ist das?', a:['Enrique Iglesias','Luis Fonsi','Ricky Martin','J Balvin'], k:1 },
  { c:'musik', d:1, yt:'9bZkp7q19f0', q:'Welcher Interpret ist das?', a:['Psy','BTS','BIGBANG','Rain'], k:0 },
  { c:'musik', d:2, yt:'OPf0YbXqDm0', q:'Welcher Sänger ist hier zu hören?', a:['Justin Timberlake','Bruno Mars','Usher','Pharrell'], k:1 },
  { c:'musik', d:1, yt:'JGwWNGJdvx8', q:'Welcher Interpret ist das?', a:['Ed Sheeran','Shawn Mendes','Sam Smith','James Arthur'], k:0 },
  { c:'musik', d:1, yt:'4NRXx6U8ABQ', q:'Welcher Interpret ist das?', a:['The Weeknd','Drake','Bruno Mars','Khalid'], k:0 },
  { c:'musik', d:1, yt:'DyDfgMOUjCI', q:'Welche Künstlerin ist das?', a:['Dua Lipa','Billie Eilish','Lorde','Olivia Rodrigo'], k:1 },
  { c:'musik', d:2, yt:'gdZLi9oWNZg', q:'Welche Band ist das?', a:['BLACKPINK','BTS','EXO','Stray Kids'], k:1 },
  { c:'musik', d:2, yt:'IHNzOHi8sJs', q:'Welche Gruppe ist das?', a:['TWICE','BLACKPINK','Red Velvet','ITZY'], k:1 },
  { c:'musik', d:2, yt:'Zi_XLOBDo_Y', q:'Welcher Interpret ist das?', a:['Prince','Michael Jackson','Lionel Richie','Stevie Wonder'], k:1 },
  { c:'musik', d:2, yt:'fJ9rUzIMcZQ', q:'Welche Band ist das?', a:['The Beatles','Queen','Led Zeppelin','The Rolling Stones'], k:1 },
  { c:'musik', d:2, yt:'hTWKbfoikeg', q:'Welche Band ist das?', a:['Pearl Jam','Nirvana','Soundgarden','Foo Fighters'], k:1 },
  { c:'musik', d:1, yt:'dQw4w9WgXcQ', q:'Welcher Interpret ist das?', a:['George Michael','Rick Astley','Wham!','a-ha'], k:1 },
  { c:'musik', d:2, yt:'7YuAzR2XVAM', q:'Welcher Rapper ist das?', a:['Dr. Dre','Eminem','50 Cent','Jay-Z'], k:1 },
  { c:'musik', d:2, yt:'qrO4YZeyl0I', q:'Welche Künstlerin ist das?', a:['Katy Perry','Lady Gaga','Madonna','Rihanna'], k:1 },
  { c:'musik', d:2, yt:'CevxZvSJLk8', q:'Welche Künstlerin ist das?', a:['Lady Gaga','Katy Perry','Kesha','Pink'], k:1 },
  { c:'musik', d:1, yt:'2Vv-BfVoq4g', q:'Welcher Interpret ist das?', a:['Ed Sheeran','Shawn Mendes','Lewis Capaldi','Niall Horan'], k:0 },
  { c:'musik', d:1, yt:'nfWlot6h_JM', q:'Welche Künstlerin ist das?', a:['Taylor Swift','Selena Gomez','Katy Perry','Ariana Grande'], k:0 },
  { c:'musik', d:1, yt:'YQHsXMglC9A', q:'Welche Künstlerin ist das?', a:['Adele','Sam Smith','Florence Welch','Lana Del Rey'], k:0 },
  { c:'musik', d:2, yt:'dvgZkm1xWPE', q:'Welche Band ist das?', a:['Coldplay','Imagine Dragons','OneRepublic','The Killers'], k:0 },
  { c:'musik', d:2, yt:'7wtfhZwyrcc', q:'Welche Band ist das?', a:['Imagine Dragons','Twenty One Pilots','OneRepublic','AWOLNATION'], k:0 },
  { c:'musik', d:2, yt:'r7qovpFAGrQ', q:'Welcher Interpret ist das?', a:['Lil Nas X','Travis Scott','Post Malone','DaBaby'], k:0 },
  { c:'musik', d:3, yt:'2vjPBrBU-TM', q:'Welche Künstlerin ist das?', a:['Sia','Adele','Florence Welch','Halsey'], k:0 },
  { c:'musik', d:2, yt:'450p7goxZqg', q:'Welcher Interpret ist das?', a:['Bruno Mars','John Legend','Sam Smith','Maroon 5'], k:1 },
  { c:'musik', d:3, yt:'QK8mJJJvaes', q:'Welcher Interpret ist das?', a:['Macklemore & Ryan Lewis','Eminem','Drake','Flo Rida'], k:0 },
  { c:'musik', d:2, yt:'1w7OgIMMRc4', q:'Welche Band ist das?', a:['AC/DC','Guns N’ Roses','Aerosmith','Bon Jovi'], k:1 },
  { c:'musik', d:3, yt:'btPJPFnesV4', q:'Welche Band ist das?', a:['Survivor','Journey','Europe','Toto'], k:0 },
  { c:'musik', d:2, yt:'IcrbM1l_BoI', q:'Welcher DJ ist das?', a:['Avicii','Calvin Harris','David Guetta','Kygo'], k:0 },
  { c:'musik', d:2, yt:'pRpeEdMmmQ0', q:'Welche Künstlerin ist das?', a:['Jennifer Lopez','Shakira','Beyoncé','Rihanna'], k:1 },
  { c:'musik', d:2, yt:'8UVNT4wvIGY', q:'Welcher Interpret ist das?', a:['Gotye','Sam Smith','James Blunt','Passenger'], k:0 },
  { c:'musik', d:1, yt:'ZbZSe6N_BXs', q:'Welcher Interpret ist das?', a:['Pharrell Williams','Bruno Mars','will.i.am','Justin Timberlake'], k:0 },
  { c:'musik', d:2, yt:'L_jWHffIx5E', q:'Welche Band ist das?', a:['Smash Mouth','Blink-182','Green Day','Sum 41'], k:0 },
  { c:'musik', d:2, yt:'djV11Xbc914', q:'Welche Band ist das?', a:['a-ha','Duran Duran','Tears for Fears','Depeche Mode'], k:0 },
  { c:'musik', d:2, yt:'KQ6zr6kCPj8', q:'Welcher Act ist das?', a:['LMFAO','Black Eyed Peas','Pitbull','Flo Rida'], k:0 },
  { c:'musik', d:2, yt:'hT_nvWreIhg', q:'Welche Band ist das?', a:['OneRepublic','Coldplay','Maroon 5','The Script'], k:0 },
  { c:'musik', d:2, yt:'09R8_2nJtjg', q:'Welche Band ist das?', a:['Maroon 5','The Weeknd','OneRepublic','Train'], k:0 },
  { c:'musik', d:1, yt:'fRh_vgS2dFE', q:'Welcher Interpret ist das?', a:['Justin Bieber','Shawn Mendes','Charlie Puth','Zayn'], k:0 },
  { c:'musik', d:1, yt:'TUVcZfQe-Kw', q:'Welche Künstlerin ist das?', a:['Dua Lipa','Ariana Grande','Doja Cat','Bebe Rexha'], k:0 },
  { c:'musik', d:2, yt:'RBumgq5yVrA', q:'Welcher Interpret ist das?', a:['Passenger','James Bay','Ed Sheeran','George Ezra'], k:0 },
  { c:'musik', d:1, yt:'gdZLi9oWNZg', q:'Welcher Song ist das?', a:['Butter','Dynamite','Permission to Dance','Life Goes On'], k:1 },

  /* --- "Aus welchem Jahrzehnt?" --- */
  { c:'musik', d:2, yt:'djV11Xbc914', q:'Aus welchem Jahrzehnt stammt dieser Hit?', a:['70er','80er','90er','2000er'], k:1 },
  { c:'musik', d:2, yt:'fJ9rUzIMcZQ', q:'Aus welchem Jahrzehnt stammt dieser Song?', a:['60er','70er','80er','90er'], k:1 },
  { c:'musik', d:2, yt:'Zi_XLOBDo_Y', q:'Aus welchem Jahrzehnt stammt dieser Song?', a:['70er','80er','90er','2000er'], k:1 },
  { c:'musik', d:3, yt:'1w7OgIMMRc4', q:'Aus welchem Jahrzehnt stammt dieser Song?', a:['80er','90er','2000er','70er'], k:0 },
  { c:'musik', d:2, yt:'btPJPFnesV4', q:'Aus welchem Jahrzehnt stammt dieser Song?', a:['70er','80er','90er','2000er'], k:1 },
  { c:'musik', d:2, yt:'hTWKbfoikeg', q:'Aus welchem Jahrzehnt stammt dieser Song?', a:['80er','90er','2000er','2010er'], k:1 },
  { c:'musik', d:1, yt:'9bZkp7q19f0', q:'Aus welchem Jahrzehnt stammt dieser Hit?', a:['2000er','2010er','2020er','90er'], k:1 },
  { c:'musik', d:1, yt:'kJQP7kiw5Fk', q:'Aus welchem Jahrzehnt stammt dieser Hit?', a:['2000er','2010er','2020er','90er'], k:1 },
  { c:'musik', d:2, yt:'gdZLi9oWNZg', q:'Aus welchem Jahrzehnt stammt dieser Hit?', a:['2000er','2010er','2020er','90er'], k:2 },
  { c:'musik', d:1, yt:'r7qovpFAGrQ', q:'Aus welchem Jahrzehnt stammt dieser Hit?', a:['2000er','2010er','2020er','90er'], k:1 },
  { c:'musik', d:2, yt:'ZbZSe6N_BXs', q:'Aus welchem Jahrzehnt stammt dieser Hit?', a:['2000er','2010er','2020er','90er'], k:1 },
  { c:'musik', d:2, yt:'pRpeEdMmmQ0', q:'Aus welchem Jahrzehnt stammt dieser WM-Song?', a:['2000er','2010er','2020er','90er'], k:1 },
  { c:'musik', d:2, yt:'4NRXx6U8ABQ', q:'Aus welchem Jahrzehnt stammt dieser Hit?', a:['2000er','2010er','2020er','90er'], k:1 },
  { c:'musik', d:2, yt:'dQw4w9WgXcQ', q:'Aus welchem Jahrzehnt stammt dieser Song?', a:['70er','80er','90er','2000er'], k:1 },
];

/* ===== INTRO guessing (first seconds of a series/cartoon opening) =====
   yt = YouTube id. Plays muted from start to `end` seconds. Guess the show.
   IDs from official channels (Nick, Pokémon, HBO, Netflix, Cartoon Network …). */
const INTRO = [
  { c:'film', d:1, yt:'r9L4AseD-aA', end:9, q:'Welche Serie ist das?', a:['SpongeBob Schwammkopf','Adventure Time','Gravity Falls','Phineas und Ferb'], k:0 },
  { c:'film', d:1, yt:'R4GIyJxvk94', end:9, q:'Welche Serie ist das?', a:['Digimon','Pokémon','Yu-Gi-Oh!','Beyblade'], k:1 },
  { c:'film', d:1, yt:'aPzS3QYb868', end:9, q:'Welche Serie ist das?', a:['Family Guy','Die Simpsons','Futurama','South Park'], k:1 },
  { c:'film', d:2, yt:'NpnQ2oIRgB0', end:10, q:'Welche Serie ist das?', a:['Friends','Der Prinz von Bel-Air','Two and a Half Men','How I Met Your Mother'], k:1 },
  { c:'film', d:2, yt:'Niu9Zmrx0p8', end:9, q:'Welche Serie ist das?', a:['Friends','Seinfeld','The Big Bang Theory','New Girl'], k:0 },
  { c:'film', d:2, yt:'s7L2PVdrb_8', end:10, q:'Welche Serie ist das?', a:['Vikings','Game of Thrones','The Witcher','The Last Kingdom'], k:1 },
  { c:'film', d:1, yt:'04WIdoIPjbI', end:9, q:'Welche Serie ist das?', a:['Feuerwehrmann Sam','PAW Patrol','Bob der Baumeister','Peppa Wutz'], k:1 },
  { c:'film', d:1, yt:'wulejb3mZK0', end:9, q:'Welche Serie ist das?', a:['Peppa Wutz','PAW Patrol','Bluey','Caillou'], k:0 },
  { c:'film', d:2, yt:'-RcPZdihrp4', end:9, q:'Welche Serie ist das?', a:['Dark','Stranger Things','The OA','Wednesday'], k:1 },
  { c:'film', d:2, yt:'d1EnW4kn1kg', end:9, q:'Welche Serie ist das?', a:['Naruto','Avatar – Der Herr der Elemente','Dragon Ball','One Piece'], k:1 },
  { c:'film', d:2, yt:'cvDxko2Zm0Q', end:9, q:'Welche Serie ist das?', a:['Adventure Time','Gravity Falls','Steven Universe','Regular Show'], k:0 },
  { c:'film', d:2, yt:'GcgDuB6ShyY', end:12, q:'Welcher Anime ist das?', a:['Naruto','Dragon Ball','One Piece','Bleach'], k:0 },
  { c:'film', d:2, yt:'R4vjJrGeh1c', end:12, q:'Welcher Anime ist das?', a:['Naruto','Dragon Ball Z','Pokémon','Digimon'], k:1 },
  { c:'film', d:2, yt:'IoX2QU822qY', end:10, q:'Welche Serie ist das?', a:['DuckTales','Chip und Chap','TaleSpin','Darkwing Duck'], k:0 },
];

/* ===== AUDIO guessing (only sound, video hidden — tap to play) =====
   yt = YouTube id. Player is covered; you guess by ear. */
const AUDIO = [
  /* songs */
  { c:'musik', d:1, yt:'kJQP7kiw5Fk', q:'Welcher Song ist das? (nur Ton)', a:['Bailando','Despacito','Macarena','Vivir Mi Vida'], k:1 },
  { c:'musik', d:1, yt:'9bZkp7q19f0', q:'Welcher Song ist das? (nur Ton)', a:['Harlem Shake','Gangnam Style','Gentleman','Macarena'], k:1 },
  { c:'musik', d:2, yt:'OPf0YbXqDm0', q:'Welcher Song ist das? (nur Ton)', a:['24K Magic','Uptown Funk','Treasure','Finesse'], k:1 },
  { c:'musik', d:1, yt:'JGwWNGJdvx8', q:'Welcher Song ist das? (nur Ton)', a:['Perfect','Shape of You','Photograph','Galway Girl'], k:1 },
  { c:'musik', d:2, yt:'fJ9rUzIMcZQ', q:'Welcher Song ist das? (nur Ton)', a:['We Will Rock You','Bohemian Rhapsody','Somebody to Love','Don’t Stop Me Now'], k:1 },
  { c:'musik', d:2, yt:'Zi_XLOBDo_Y', q:'Welcher Song ist das? (nur Ton)', a:['Beat It','Billie Jean','Thriller','Smooth Criminal'], k:1 },
  { c:'musik', d:1, yt:'4NRXx6U8ABQ', q:'Welcher Song ist das? (nur Ton)', a:['Save Your Tears','Blinding Lights','Starboy','The Hills'], k:1 },
  { c:'musik', d:1, yt:'dQw4w9WgXcQ', q:'Welcher Song ist das? (nur Ton)', a:['Take On Me','Never Gonna Give You Up','Africa','Tainted Love'], k:1 },
  { c:'musik', d:2, yt:'hTWKbfoikeg', q:'Welcher Song ist das? (nur Ton)', a:['Come As You Are','Smells Like Teen Spirit','In Bloom','Lithium'], k:1 },
  { c:'musik', d:1, yt:'gdZLi9oWNZg', q:'Welcher Song ist das? (nur Ton)', a:['Butter','Dynamite','Boy with Luv','DNA'], k:1 },
  { c:'musik', d:1, yt:'DyDfgMOUjCI', q:'Welcher Song ist das? (nur Ton)', a:['bad guy','lovely','Therefore I Am','Happier Than Ever'], k:0 },
  { c:'musik', d:2, yt:'60ItHLz5WEA', q:'Welcher Song ist das? (nur Ton)', a:['Alone','Faded','Sing Me to Sleep','The Spectre'], k:1 },
  { c:'musik', d:1, yt:'ZbZSe6N_BXs', q:'Welcher Song ist das? (nur Ton)', a:['Happy','Get Lucky','Freedom','Blurred Lines'], k:0 },
  { c:'musik', d:1, yt:'7wtfhZwyrcc', q:'Welcher Song ist das? (nur Ton)', a:['Believer','Thunder','Radioactive','Demons'], k:0 },
  { c:'musik', d:1, yt:'nfWlot6h_JM', q:'Welcher Song ist das? (nur Ton)', a:['Blank Space','Shake It Off','Bad Blood','Style'], k:1 },
  { c:'musik', d:1, yt:'YQHsXMglC9A', q:'Welcher Song ist das? (nur Ton)', a:['Hello','Someone Like You','Rolling in the Deep','Easy on Me'], k:0 },
  { c:'musik', d:2, yt:'IHNzOHi8sJs', q:'Welcher Song ist das? (nur Ton)', a:['Kill This Love','DDU-DU DDU-DU','How You Like That','Boombayah'], k:1 },
  { c:'musik', d:3, yt:'1w7OgIMMRc4', q:'Welcher Song ist das? (nur Ton)', a:['November Rain','Sweet Child O’ Mine','Paradise City','Welcome to the Jungle'], k:1 },
  /* game themes */
  { c:'gaming', d:1, yt:'nsff88sufkI', q:'Welches Game-Theme ist das?', a:['Super Mario','The Legend of Zelda','Sonic','Pac-Man'], k:0 },
  { c:'gaming', d:2, yt:'cGufy1PAeTU', q:'Welches Game-Theme ist das?', a:['Final Fantasy','The Legend of Zelda','Skyrim','Metroid'], k:1 },
  { c:'gaming', d:1, yt:'tehZmdXbMac', q:'Welches Game-Theme ist das?', a:['Pac-Man','Tetris','Pong','Snake'], k:1 },
  { c:'gaming', d:2, yt:'G-i8HYi1QH0', q:'Welches Game-Theme ist das?', a:['Sonic the Hedgehog','Super Mario','Crash Bandicoot','Rayman'], k:0 },
  { c:'gaming', d:2, yt:'aBkTkxKDduc', q:'Welches Game-Theme ist das?', a:['Terraria','Minecraft','Roblox','Stardew Valley'], k:1 },
  { c:'gaming', d:3, yt:'gChDf7lTEQQ', q:'Welches Game-Theme ist das?', a:['The Witcher','Skyrim','Dragon Age','Dark Souls'], k:1 },
];

module.exports = { TF, EST, LISTS, EMOJI, VIDEO, INTRO, AUDIO };
